### ISSUE TITLE
Unable to install storjshare-daemon on Ubuntu Server

### ISSUE THREAD

**Issue by golyalpha** [Storj/storjshare-daemon#104]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
NOT INSTALLED
```

Replace the values below using the output from `node --version`.

```
v4.2.6
```

### Expected Behavior
Install storjshare-daemon.

### Actual Behavior

Crashes with some errors along the lines of "permission denied" and outputs the following logs.

```
File too large - attached
```
[npm-debug.txt](https://github.com/Storj/storjshare-daemon/files/880187/npm-debug.txt)

### Steps to Reproduce

1. Boot Ubuntu Server (16.04 LTS)
2. Follow the instalation instructions
3. Grab some cake while it's installing, before it spews out the error.

**Comment by littleskunk** [comment]
`checkPermissions Missing write access to /usr/local/lib`

**Comment by bookchin** [comment]
Sounds like you are root. You need to add `--unsafe-perm` option to the install command.

**Comment by bookchin** [comment]
Excuse, sounds like you are *not* root - use `sudo` or install node.js via NVM as suggested in the README.

**Comment by golyalpha** [comment]
In root shell (over sudo) I get a different type of error. Currently don't have access to the server, but will later today. Stand-by for log from npm.

**Comment by golyalpha** [comment]
Ok, so, here's the log from when in the root shell:
[npm-debug.txt](https://github.com/Storj/storjshare-daemon/files/887803/npm-debug.txt)

**Comment by golyalpha** [comment]
@bookchin @littleskunk

**Comment by littleskunk** [comment]
Wrong nodejs version.
