### ISSUE TITLE
Error: ENOENT: no such file or directory, open '' on storejshare daemon command

### ISSUE THREAD

**Issue by naqvijafar91** [Storj/storjshare-daemon#106]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.5.1, core: 6.4.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

storejshare daemon command should start the daemon 

### Actual Behavior

I am getting this:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open ''
    at Error (native)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1.  storjshare daemon
2. ...
![storejissue](https://cloud.githubusercontent.com/assets/13377690/24767417/7f289b7e-1b1c-11e7-95a4-b7b146f543be.png)

3. ...

**Comment by aceman444** [comment]
Can you check what value do you have for the  "loggerOutputFile" variable in your .json config of the share? Do you have empty value ("") ?

**Comment by henningvs** [comment]
I get exactly the same problem.
My config variable looks like this:

`"daemonLogFilePath": "~/.config/storjshare/logs/storj-daemon.log",`

And the error is

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '~/.config/storjshare/logs/storj-daemon.log'
    at Error (native)
```

**Comment by bookchin** [comment]
You need to use an absolute path, the tilda is a function of your shell.

**Comment by aceman444** [comment]
I get the same error when using empty path ("") which according to the comment in the config file will use the default path. But it does not, it crashes the daemon.
