### ISSUE TITLE
Storjshare stops on having too many open files

### ISSUE THREAD

**Issue by KeirDavis1** [Storj/storjshare-daemon#109]
### Package Versions

user@storj01:~$ sudo storjshare -V

```
  * daemon: 2.5.1, core: 6.4.0, protocol: 1.1.0
```

Node version

```
v7.8.0
```

### Expected Behavior

To not stop the share on finding this error. It is not actually caused by Storjshare itself, but the NFS server I'm saving the files to. Maybe a try/catch for it?

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":2413480,\"address\":\"104.196.187.29\",\"port\":8464,\"nodeID\":\"dca6b120727d5e4c1ea3ad8aa9c9f9c93f42fb11\",\"lastSeen\":1492111648536}","timestamp":"2017-04-14T01:38:45.702Z"}
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: IO error: /storj2/dat/sharddata.kfs/194.s/000119.log: Too many open files
```

And that's the end of the log

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

```
Not sure on how to reproduce other than leaving the
storjshare-daemon running a farm for a while. 

Default configuration generated from command line. 
Using a 1TB NFS share. 
```

I don't want to have to keep checking on the storj-shares if they just stop

**Comment by ordtrogen** [comment]
Let me add that I see very similar things in my logs. Entry just prior to the IO Error is different. See log snippets below. In my case, however, the share gets restarted and keeps running so I don't need to check just to keep it running.

Snippet 1

{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"6.3.2\",\"protocol\":\"1.1.0\",\"address\":\"37.49.209.24\",\"port\":45703,\"nodeID\":\"37eb9ae7dc03cb47bfd31db96fb46e80eeaa9276\",\"lastSeen\":1492106434194}","timestamp":"2017-04-13T18:00:42.604Z"}
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: IO error: /home/USB_STORJ/storjshare/sharddata.kfs/144.s/000919.ldb: Too many open files
{"level":"info","message":"node created with nodeID 37e81184958887b9816b4b17ca1ef6eff3abdb62","timestamp":"2017-04-13T18:01:11.785Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: -4518 ms","timestamp":"2017-04-13T18:01:21.851Z"}


Snippet 2:

{"level":"info","message":"replying to message to ae793b267273d1a960b893073be2e83283570d17","timestamp":"2017-04-14T02:56:10.088Z"}
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: IO error: /home/USB_STORJ/storjshare/sharddata.kfs/124.s/001279.ldb: Too many open files
{"level":"info","message":"node created with nodeID 37e81184958887b9816b4b17ca1ef6eff3abdb62","timestamp":"2017-04-14T02:56:32.979Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: -3831 ms","timestamp":"2017-04-14T02:56:40.823Z"}

**Comment by 3cl1ps** [comment]
* daemon: 2.4.4, core: 6.2.1, protocol: 1.1.0

events.js:160
throw er; // Unhandled 'error' event
^

Error: IO error: /home/eclips/farm/sharddata.kfs/110.s/008833.ldb: Too many open files
at Error (native)

Seems like a random crash, no way to reproduce. small share of 500gb.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/666

Close it please.
