### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by Sparc0** [Storj/storjshare-daemon#117]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.5.1, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.5
```

### Expected Behavior

It has been working for a month. But since i got over 200Gb i had this problem. 

### Actual Behavior
I have started to get to many files open.

{"level":"debug","message":"checking pending rpc callbacks for expirations","timestamp":"2017-04-28T18:14:34.337Z"}
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EMFILE: too many open files, scandir '/opt/.storj/node1/sharddata.kfs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Btable.stat (/root/.nvm/versions/node/v6.10.0/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:194:23)
    at /root/.nvm/versions/node/v6.10.0/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:182:16

My hard limit and soft limit is set on 65535.

### Steps to Reproduce
I just have to restart the node and it dies after 24-48 hours.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/666
