### ISSUE TITLE
Feature: rotating log files

### ISSUE THREAD

**Issue by guelz** [Storj/storjshare-daemon#120]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 daemon: 2.5.1, core: 6.4.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.2
```

### Expected Behavior

logfiles written to C:\User\...\.config\sorjshare\logs

### Actual Behavior

log files grow indefinitely(?) in size! @~150Mb they are not very handy anymore!

### Feature Request

1. rolling logs or create a new one each day or three and delete them after some time 
2. (for GUI_V5 make the editor to use configurable)

**Comment by gbaker3** [comment]
I second this motion. The GUI pre-v5 allowed for this and made things much more manageable.
