### ISSUE TITLE
Deleting the logfile doesn't create a fresh new one

### ISSUE THREAD

**Issue by Kojee** [Storj/storjshare-daemon#123]
### Package Versions

```
Daemon version : 2.5.1
```

```
Node version : 6.10.1
```

### Expected Behavior

When deleting the logfile of a certain node, the daemon should recreate a new empty one.

### Actual Behavior

Logfile is not recreated if not by restarting the node.

### Steps to Reproduce

1. Delete the file located at [writepath] (e.g.  $HOME/.config/storjshare/logs/) chosen when the node was created with `storjshare create`

**Comment by littleskunk** [comment]
`>logfile` will clear the logfile without deleting it.

Close it please.

**Comment by littleskunk** [comment]
Looks like GUI user are running into the same issue. Let me explain the solution in detail.

Never ever delete logfile while the application is still running. Other applications will not create a new logfile as well. Only clearing the logfile is allowed.

Linux: `>/path/to/logfile`
Windows cmd: `break>"C:\path\to\logfile"`
Windows powershell: `Clear-Content "C:\path\to\logfile"`
