### ISSUE TITLE
Node Storage usage is being truncated

### ISSUE THREAD

**Issue by Fluoroantimonicacid** [Storj/storjshare-daemon#124]
### Package Versions

Replace the values below using the output from `storjshare --version`.

  * daemon: 2.5.1, core: 6.4.2, protocol: 1.1.0

Replace the values below using the output from `node --version`.
v6.10.2

### Expected Behavior

Storjshare status should truncate the decimal places to fit the Shared space in the shared column, or allow us to re-size the columns to fit all sizes.

### Actual Behavior

For some values, the Units are truncated when a little over 1.0 of a unit is used, for example:

┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ befd20dc7da89b6390e2d8ea21077b23ecd6f4dd    │ running  │ 16h 56m… │ 0        │ 178      │ 1006.55… │
│   → /storj/0                                │          │          │          │          │ (23%)    │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤

1006.55 MB is being truncated to 1006.55 instead of being displayed as 1006.5 MB, 1GB, or 1.00 GB

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Fill a share with a little over 1 KB or 1MB or 1 GB and run the storjshare status command.

**Comment by SadTomato** [comment]
You can change the size of the column.
First of all, find storjshare-status: `which storjshare-status`.
Then open this file in editor and change the size of the column at line 112.

**Comment by NutterzUK** [comment]
https://github.com/Storj/storjshare-daemon/compare/master...NutterzUK:patch-1
