### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-daemon#125]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

No error

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: IO error: /home/jadaka/StorjL/STORJ03/sharddata.kfs/203.s/002076.ldb: Too many open files
    at Error (native)
```

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/666

Close please.
