### ISSUE TITLE
Configs folder not created initially

### ISSUE THREAD

**Issue by PhABC** [Storj/storjshare-daemon#126]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.5.1, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
4.2.6
```

### Expected Behavior

Using the storjshare create --sjcx 1vEkUGAPPrMWMdDvfmTfNH5ps9xwGyjhH should work on fresh install.

### Actual Behavior

Error message :
```
failed to write config, reason: ENOENT: no such file or directory, open '/home/USER/snap/storjshare/6/.config/storjshare/configs/ebde9bfdb36a29bd201929574bd4fdcac88a49a2.json'
```
### Steps to Reproduce

1. snap install storjshare
2. storjshare create --sjcx=1vEkUGAPPrMWMdDvfmTfNH5ps9xwGy
3. Error

This happened both on my linux and windows machine. 

### Workaround

I just need to create the folder configs under .config/storjshare/ and it works as expected.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/122

Close please.
