### ISSUE TITLE
docker volume mount can't be used

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-daemon#135]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

Please describe the program's expected behavior.

Utilize a mounted volume within a docker container as a storj data repo.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

When running within a docker container that has a volume mount (https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume) and pointing storjshare to this directory....when you attempt to start storjshare it says  failed to start share, reason: invalid storage size   (I used 1GB and even 1MB to test).  It appears it is not detecting the free space of the volume correctly or something else is going on.  I can manually write to the location outside storjshare so I know the volume works.

If I remove the mount and use the folder in the local container, it works fine.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. In Windows 10 or Server 2016 enable containers
2. make a folder on the host C:\storjcontainer
3. make a folder on the host C:\storjdata
4.
```
docker run -it -v "C:\storjcontainer:C:\storj" computeronix/storjshare-daemon:windows ""storjshare create --sjcx 1xDGKeB31UeNkaRffzYcW6EMC2qTv4YZv --size 1GB --storage ""C:\storjdata"" --noedit --logfile ""C:\storj\storj.log"" -o ""C:\storj\storj.config""""
```
5.
```
docker run -it -v "C:\storjdata:C:\storjdata" -v "C:\storjcontainer:C:\storj" computeronix/storjshare-daemon:windows "cmd /c 'storjshare daemon start && storjshare start -c ""C:\storj\storj.config"" && powershell'"
```

I have not tested with the ubuntu docker image but will do once i get a system up for that too

**Comment by computeronix** [comment]
one suggestion is upon failure of the reason for storj size  if you configured a log output file can you put in more details in the log file then exit?

**Comment by computeronix** [comment]
Ubuntu is not affected within a docker, it works as expected

**Comment by computeronix** [comment]
When running the above example here is a sample screenshot showing the error as well as showing that you can write to the directory from within the docker and get to the file on the host

![image](https://cloud.githubusercontent.com/assets/19168174/26036509/fb0e88e0-38ac-11e7-9561-4d6344fa7c47.png)

**Comment by phutchins** [comment]
@computeronix I've also experienced this behaviour and have done some troubleshooting. I believe it's in the way that disk space is calculated for mounts vs inside the container. If I get some time soon I may knock this one out...

**Comment by bookchin** [comment]
I noticed that you are using windows. I have a feeling it's the use of `wmic logicaldisk ...` windows command. Can you confirm this is windows specific?

**Comment by bookchin** [comment]
(Which like @phutchins says, is how we get disk space - but only on windows)

**Comment by computeronix** [comment]
that works on windows

PS C:\> wmic logicaldisk
Access  Availability  BlockSize  Caption  Compressed  ConfigManagerErrorCode  ConfigManagerUserConfig  CreationClassName  Description       DeviceID  D
riveType  ErrorCleared  ErrorDescription  ErrorMethodology  FileSystem  FreeSpace    InstallDate  LastErrorCode  MaximumComponentLength  MediaType  Nam
e  NumberOfBlocks  PNPDeviceID  PowerManagementCapabilities  PowerManagementSupported  ProviderName  Purpose  QuotasDisabled  QuotasIncomplete  QuotasR
ebuilding  Size         Status  StatusInfo  SupportsDiskQuotas  SupportsFileBasedCompression  SystemCreationClassName  SystemName    VolumeDirty  Volum
eName  VolumeSerialNumber
0                                C:       FALSE                                                        Win32_LogicalDisk  Local Fixed Disk  C:        3
                                                            NTFS        21190148096                              255                     12         C:

           21339549696                      FALSE               TRUE                          Win32_ComputerSystem     C07F2CE919FB  FALSE
       2CD53941

**Comment by AlexeyALeonov** [comment]
I'm solved this with `subst w: C:\Volume` command before daemon start.
