### ISSUE TITLE
Attempting to start share gives error

### ISSUE THREAD

**Issue by Virtix21** [Storj/storjshare-daemon#136]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.5.1, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v4.2.6
```

### Expected Behavior

Self-explanatory

### Actual Behavior
```
storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/configname.json
  failed to start share, reason: eacces: permission denied, scandir '/home/sdc/storj'
```
### Steps to Reproduce
```
Trying to run storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/configname.json
gives the error
  failed to start share, reason: eacces: permission denied, scandir '/home/sdc/storj'
```
It seems like everything is in-order in the config.

**Comment by jfnz** [comment]
I'm having the same exact issue and it's driving me nuts. Glad to see it's not just me!

### Package Versions

  * daemon: 2.5.1, core: 6.4.2, protocol: 1.1.0

### Expected Behavior

Program starts

### Actual Behavior

root@xxxx:/mount/storj# storjshare start --config /mount/storj/bf298b2663c17d18b8ea658d693876f11897ac47.json

  failed to start share, reason: failed to read config at /mount/storj/bf298b2663c17d18b8ea658d693876f11897ac47.json


### Steps to Reproduce

This is a fresh install.

**Comment by bookchin** [comment]
The `eacces: permission denied` means the process doesn't have access rights to the storage location. You must run as an appropriate user or grant your user access to that location.

**Comment by jfnz** [comment]
I can confirm the user it's running is does have the ability to write to the location.

**Comment by Virtix21** [comment]
Does the daemon run as another user? I've tried to do this as root, and still the same issue.

**Comment by jfnz** [comment]
Yeah something is definitely screwy here. Not sure why we closed this bug off so quickly..

**Comment by Virtix21** [comment]
Found a solution yet @jfnz?

**Comment by jfnz** [comment]
Gave up troubleshooting, redeployed Ubuntu 16.04.02 - worked with a fresh install, so not sure what was happening. I was due an upgrade from 14.04 anyway :)

**Comment by timdv91** [comment]
Got same problem when I change the share path.
User has read and write access to the actual path but got same error.

If i leave the share on the default path it seems to work fine.
Default path on my machine: /home/'username'/snap/storjshare/7/.config/storjshare/shares/'shareID'/

If you want it on another harddrive, maybe it will work with a shortcut from the default location to another location as fast fix.
