### ISSUE TITLE
Shared showing "(...%)" instead of actual shared value

### ISSUE THREAD

**Issue by jfnz** [Storj/storjshare-daemon#138]
Okay, you'll remember the previous bugs I've logged having issues with getting storjshare running at all. I was a due an upgrade to Ubuntu 16.04 LTS from 14.04 on this box anyway so have formatted and reinstalled, and have run head-first in to another potential issue. Details to follow.

### Package Versions
```
daemon = 2.5.4
core = 6.4.2
protocol = 1.1
node = v6.10.3
npm = 3.10.10
nvm = 0.33.2
```

### Expected Behavior
I would expect storjshare-status should return used shared amounts, similar to the way it would in the GUI package.

Verified contracts have been recieved written to disk as follows, so does not appear to be related to permissions, etc.

```
user@hostname:~$ du -h /storage/storj/
<truncated>
2.4M    /storage/storj/sharddata.kfs
164K    /storage/storj/contracts.db
2.5M    /storage/storj/

```

### Actual Behavior

Displaying the storjshare-status output shows that the shared amount is blank. I would expect this to reflect the values listed above in terms of contracts received. This has not resolved after almost 5 hours of running, I had expected it was a temporary issue due to a newly provisioned node, etc.

```
user@hostname:~$ storjshare-status

┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    │ running  │ 4h 48m … │ 0        │ 166      │ ...      │
│   → /storage/storj/                         │          │          │          │          │ (...%)   │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

```

### Steps to Reproduce

Pretty much a brand new, clean install of Ubuntu 16.04.02 LTS with the latest storjshare, installed as per the how-to guide in the cli section.

Config for reference: [storj-config.txt](https://github.com/Storj/storjshare-daemon/files/995724/storj-config.txt)

**Comment by jfnz** [comment]
11 hours later only another 0.2MB has been written, shared is still blank.

```
┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    │ running  │ 15h 51m… │ 0        │ 167      │ ...      │
│   → /storage/storj/                         │          │          │          │          │ (...%)   │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

```
And

```
user@hostname:~$ du -h /storage/storj/
16K     /storage/storj/sharddata.kfs/246.s
<truncated>
2.5M    /storage/storj/sharddata.kfs
172K    /storage/storj/contracts.db
2.7M    /storage/storj/
```

Any ideas?

**Comment by jfnz** [comment]
Resolved itself after 24 hours.. Odd, but oh well 👍 

```
user@hostname:~$ storjshare-status

┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    │ running  │ 1d 5m 3… │ 0        │ 181      │ 2.43GB   │
│   → /storage/storj/                         │          │          │          │          │ (0%)     │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
```

**Comment by njj** [comment]
@jfnz Any ideas on what this was?  I'm seeing it.

**Comment by jfnz** [comment]
@njj No, the linked thread has the recommendation of running kfs compact but that didn't fix it. The mods on this project are so overly anxious to close tickets before verifying whether the problem is indeed legitimate or fixed I couldn't be bothered coming back to complain that wasn't it. Every legit issue I've had has been shut with a dismissive unhelpful reply that has usually been resolved by me tearing down and reinstalling things.

Moaning aside I deleted the 30GB worth of data and created a new node which has fixed it. I guess some sort of corruption in the database maybe.

**Comment by jfnz** [comment]
@njj - looks like it was purely cosmetic and resolved itself after some time.

**Comment by njj** [comment]
@jfnz I saw you rant :) . Thanks for letting me know, I'll be aware of that if I post any issues myself.  I'll just keep refreshing to see if it fixes itself.  I accidentally had it running on a rather small amount (2 GB), and it immediately showed the shared amount.  I recreated and pointed it at around 6TB and now its taking a bit.  Perhaps its a calculation thing?

**Comment by njj** [comment]
@jfnz I killed everything and made a new one, now its showing shared 🤷‍♂️
