### ISSUE TITLE
Why does the daemon not restart a stopped share?

### ISSUE THREAD

**Issue by SjonHortensius** [Storj/storjshare-daemon#140]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v7.10.0
```

### Expected Behavior

I run `storjshare-daemon -F` as a systemd service. The daemon seems useless however; when the share stops, the daemon logs this, but does not restart it. Why not?

### Actual Behavior

The daemon notices that the share breaks, but does not restart it. It requires manual intervention to restart the share. The daemon keeps running successfully

```
storjshare-daemon[1132]: {"level":"info","message":"share f6c0e6069c4edadef3047d04fcfae8e1f37eb8e7 exited with code 1","timestamp":"2017-05-16T07:34:33.123Z"}
storjshare-daemon[1132]: {"level":"info","message":"got status query","timestamp":"2017-05-16T07:35:12.452Z"}
```

**Comment by littleskunk** [comment]
Please install nodejs lts (v6.10.3 at the Moment) and try again.

**Comment by matt08** [comment]
I have the same problem.

`storjshare --version

  * daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0`

`node --version
v6.9.1`

After i tried to restart node manually i got the error:
`failed to start share, reason: insufficient system resources available`

1 cpu / 1 core / 1 node on VPS (OpenVZ).

After "storjshare killall" and fresh start, node running correctly, but it's stopped after a few hours.

**Comment by donerler** [comment]
I also have the same issue. Every day a share is restarted unsuccessfully, When manually restarting the share I get the message `failed to start share, reason: insufficient system resources available`
`daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0`
`node v6.11.0`

**Comment by bsdemon** [comment]
Same problem here.
`storjshare --version daemon: 3.3.0, core: 6.5.0, protocol: 1.1.0`
`node --version v6.10.2`
I can run only 2 nodes

**Comment by tempestb** [comment]
Stale.  For further help join https://community.storj.io and the channel #storjshare
