### ISSUE TITLE
Storjshare Daemon 3.0 shuts down when starting a node.

### ISSUE THREAD

**Issue by tempestb** [Storj/storjshare-daemon#151]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.0.0, core: 6.4.3, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

Storjshare Daemon (Starts)
Storjshare start --config ~/config.json
Storjshare Status (Shows status of running node)

### Actual Behavior

Storjshare Daemon (Starts)
Storjshare start --config ~/config.json
Storjshare Status (Daemon is not running)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upgrade to 3.0
2. ...
3. ...

**Comment by Altosaxophony** [comment]
Same here

**Comment by tempestb** [comment]
Update fixes the issue.  Thanks.
