### ISSUE TITLE
Not able to get shards

### ISSUE THREAD

**Issue by Brossard45** [Storj/storjshare-daemon#153]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

After storjshare started, shared volume must increase as shards must be uploaded to my drive. 

### Actual Behavior

Offers are accepted but no data seems to be uploaded to my drive.

```
┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 3523c03db5021c89fd8fd1784bb07891810799de    │ running  │ 3h 43m … │ 0        │ 139      │ 1.2MB    │
│   → /mnt/storj1/                            │          │          │          │          │ (0%)     │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

```

I also can't see some logs that you specify in your troubleshooting guide, Section 12  - Step 5 : Upload Shard, like :

```
{"level":"info","message":"handling storage consignment request from 593844dc7f0076a1aeda9a6b9788af17e67c1052","timestamp":"2016-06-19T20:22:13.196Z"}
{"level":"info","message":"authorizing upload data channel for 593844dc7f0076a1aeda9a6b9788af17e67c1052","timestamp":"2016-06-19T20:22:14.953Z"}
{"level":"info","message":"replying to message to d4978f4f16d57bb831bae7db9a013a6c729032ed","timestamp":"2016-06-19T20:22:14.953Z"}
```

### Steps to Reproduce

1. Start storjshare daemon and node
2. Storj starts to acquire peers 
3. Numbers of Contracts or disk space used never changes

Please find my config file and some logs (debug level) attached : [log_and_conf.zip](https://github.com/Storj/storjshare-daemon/files/1053298/log_and_conf.zip)

Thanks for your help 😄 
Arnaud

**Comment by littleskunk** [comment]
Everything is working as expected. 300 OFFER in one hour but no shard upload is nothing to worry about. Close it please.

**Comment by Brossard45** [comment]
Hi, 
I would like to add that i attach only few hours logs, but daemon ran for some days without seeing any shard uploaded...
I'll try again during a longer period.
Thanks

**Comment by littleskunk** [comment]
If you need help please join us on https://community.storj.io

Github is not the place for support questions ;)
