### ISSUE TITLE
Default option for storjshare logs should tail logs from all nodes

### ISSUE THREAD

**Issue by madcatsu** [Storj/storjshare-daemon#159]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v7.10.0
```

### Expected Behavior

The `storjshare logs` command should default to providing tailed log output from all running nodes, this could be filtered by specifying the --nodeid parameter as current. Default log output should then provide the Node ID as an additional string/field so that external log analytics tools can pull this data apart in an easier manner.

A `storjshare logs --format json` command ideally would provide log messages in JSON format for storing logs or programatic filtering.

### Actual Behavior

Current `storjshare logs` command requires additional parameters to provide useful data. The Node ID must be known beforehand by executing the `storjshare status` command before the logs command becomes useful.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/41

Close it please.

**Comment by madcatsu** [comment]
Closed as requested :)
