### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by iBobik** [Storj/storjshare-daemon#16]
I want to farm and install Storj by Docker, but it is not intuitive what an how to use it.

Usually it works like this in Docker world:

1. I will look for Docker instructions in README on GitHub where should be example for docker pull, docker run and basic configuration.
2. If not and I see Dockerfile in the repo I will try to search for a project on hub.docker.com with a proper README and auto builds (because it is safer).

This project have no repo on the Hub (nothing connected with this repo = auto build) and in namespace "storj*", so for Docker users there is no trustworthy image what we can use without much thinking.

**Comment by monaka** [comment]
Does this make some helps?

```
FROM node:6.9.5
MAINTAINER Masaki Muranaka <monaka@monami-ya.com>
 
RUN useradd --user-group --create-home --shell /bin/false app
RUN npm install --global storjshare-daemon
 
ENV HOME=/home/app
USER app
WORKDIR /home/app
RUN mkdir -p .config/storjshare storage_root
VOLUME /home/app/.config/storjshare
VOLUME /home/app/storage_root

ENTRYPOINT [ "storjshare" ]
CMD [ "help" ]
```

**Comment by iBobik** [comment]
@monaka Yes it helps if there is not some official Docker image (soI can prepare my own), but there maybe is, just it is without docs or readme.

**Comment by littleskunk** [comment]
I have now docker access on the storj repository. I will try to setup a build job.

**Comment by littleskunk** [comment]
@computeronix added some docker files: https://github.com/Storj/storjshare-daemon/tree/master/dockerfiles

Please try it out and let us know if something is missing. If everything is fine we can go on with an automated and official docker build.

**Comment by iBobik** [comment]
As I mentioned in the first message - README, with example how to use it in
docker-compose.yml and project on Docker Hub with the same instructions and
auto builds.



Jan Pobořil

2017-03-21 0:19 GMT+01:00 littleskunk <notifications@github.com>:

**Comment by iBobik** [comment]
About Ubuntu Dockerfile, it is very space-wasting.

1. `FROM ubuntu:latest` - Ubuntu image contains many things this project
probably does not need.
2. `apt-get update`, `apt-get -y install` and `apt-get clean` should be in
one RUN instruction, so in the image layer will be only installed packages,
not files from the update command.
3. `apt-get -y dist-upgrade` and `apt-get -y upgrade` If you need another
distro version you should select it in FROM instruction, so your image will
not have two layers with both versions. Also there is probably nothing to
update because ubuntu:latest means latest.

Another issue is that this image does not start daemon - ENTRYPOINT and CMD
instruction.



Jan Pobořil

2017-03-21 14:16 GMT+01:00 Jan Pobořil <bobik@ibobik.cz>:

**Comment by computeronix** [comment]
The image file was a quick spin up to solve an issue for a community member.  Feel free to make modifications as needed.

I put the commands into one line now and removed dist-upgrade.    Update and Upgrade are still needed as the packages supplied still have some updates based on how old the ubuntu:latest build is

For autobuilding -> I am working with philip to get Storj Labs with an official docker image for Windows and various flavors of Linux

docker-compose is not needed with the solution above as docker-compose really brings in multiple services together which this docker image does not need and is overkill

Yes a readme is needed just was a quick release of some code to get this fix out there for the community member. In the meantime to use this image

storjshare-dameon does not auto run as the image does not automatically setup the storjshare-daemon for you.  Look for that (not yet) in the automation section in storjlabs of github as this image merely provides everything needed to setup storjshare

Based on the previous statement the entry point gets you into bash to allow you to continue making changes once the machine is online.

`FROM ubuntu:latest` - Ubuntu image contains many things this project
probably does not need. -- Let me know a smaller ubuntu image you would like to use that is officially prebuilt of the ubuntu community and I can test with that.  The image is pretty small as of now but it doesnt mean we cant make it smaller.

1.docker run -i -t computeronix/temp-storj-daemon-ubuntu   (I have prebuilt an image for testing)
then your in the docker container
2. Type storjshare-daemon start
3. Type storjshare create --sjcx xxxxxxx
Where xxxxx is your SJCX address
Then it will open vim with the config file and have you review the changes
Save the config file
It will then tell you a location it saved the file (or you can specify the location of the config file in the create parameter)
4. Type storjshare start --config xxxx
Where xxx is the location of the config file

Now it should be working

Feel free to look up docker create commands to see how to create the container that is always running, larger disk space (or even uses host disk space), etc.

This is more of a tool to get you off the ground running with however you want to setup your own docker container.  We will add more automation components to this overtime.

Hope this helps and look for more updates down the road too (or feel free to contribute as well)

**Comment by computeronix** [comment]
https://github.com/Storj/storjshare-daemon/pull/102
