### ISSUE TITLE
"daemonLogFilePath" directive in confg file do not support common *nix variable expansion

### ISSUE THREAD

**Issue by andreamtp** [Storj/storjshare-daemon#161]
### Package Versions

```
daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0
```

```
v6.11.0
```

### Expected Behavior

When setting "daemonLogFilePath" directive in confg file on *nix environment, I expect to be able to use common variable to refer to my home directory, like the example reported in the config file itself:

```
# cat ~/.config/storjshare/config
{
  // Bind Dnode RPC server to this port
  "daemonRpcPort": 45015,
  // Interface to bind Dnode RPC server, if your host is public, be sure to
  // leave this as "127.0.0.1" to prevent others from controlling your nodes
  // You can set this to a public address if you'd like to control your shares
  // remotely, however you must secure access on your own - you have been
  // warned
  "daemonRpcAddress": "127.0.0.1",
  // Path to write daemon log file to disk, leave blank to default to:
  // $HOME/.config/storjshare/logs/daemon.log
  "daemonLogFilePath": "$HOME/.config/storjshare/logs/daemon.log",
  // Determines how much detail is shown in the log:
  // 4 - DEBUG | 3 - INFO | 2 - WARN | 1 - ERROR | 0 - SILENT
  "daemonLogVerbosity": 3
}
```

### Actual Behavior

When using the config file above, user get the following error:

```
# node storjshare.js daemon
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '$HOME/.config/storjshare/logs/daemon.log'
    at Error (native)`
```

and also using the other common way to refer to home directory ```~``` provide similar results:

```
# node storjshare.js daemon
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '~/.config/storjshare/logs/daemon.log'
    at Error (native)`
```

### Steps to Reproduce

1. cp storjshare-daemon/example/daemon.config.json ~/.config/storjshare/config
2. set daemonLogFilePath variable to full path with the help of a env var
3. node storjshare.js daemon
3. boom...

**Comment by tempestb** [comment]
So things like $HOME and ~foo are interpreted by your shell and not the kernel.  The shell makes a replace on those and inserts the logic when the line or script is run.  Where as with Storjshare, it's using Nodejs which I'm assuming does not interpret these statements and provide a replace.   (at least not with version 6.x.x)  

AFAIK, this makes it a no-fix and it may just end up working at some point if Nodejs decides to support this convention.
