### ISSUE TITLE
Recover contracts data in case of bad sector

### ISSUE THREAD

**Issue by felixbrucker** [Storj/storjshare-daemon#163]
### Expected Behavior

If one small file in the contracts.db leveldb is corrupted it is possible to recover it without external backups.

### Actual Behavior

If even the smallest part of the leveldb is lost the whole share cant be used and has be destroyed.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. setup share
2. corrupt contracts.db file
3. can't use share anymore

As the targeted systems are desktop class hdds such failures will occur and they should not render the whole share unusable. Also it shouldn't be the users duty to backup the contracts leveldb manually.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/kfs/issues/55
