### ISSUE TITLE
Do rely on $EDITOR instead of calling directly 'vim', and failing

### ISSUE THREAD

**Issue by andreamtp** [Storj/storjshare-daemon#165]
### Package Versions

```
daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0
```

```
v6.11.0
```

### Expected Behavior

When creating an a new config, after parsing the passed parameters, the config files should be opened with the default editor on the system: storj should not looking explicitely for `vim`. 
There's no guarantee that '''vim''' will be installed: minimal images can ship 'vi' or 'nano'. 
Safest choice would be to rely on the ad hoc variable for the *nix world: 

$EDITOR

### Actual Behavior

When invoking

```
$ storjshare-create --sjcx  xxx  --storage /home/storj/storj-data/ --size 6GB --outfile /home/storj/config.json --rpcaddress xxx --logdir /home/storj/storj-data/

  * configuration written to /home/storj/config.json
  * opening in your favorite editor to tweak before running
which: no vim in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/storj/.local/bin:/home/storj/bin)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nano ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

### Steps to Reproduce

1. storjshare-create --sjcx  xxx  --storage /home/storj/storj-data/ --size 6GB --outfile /home/storj/config.json --rpcaddress xxx --logdir /home/storj/storj-data/
3. boom...

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/101

**Comment by aleitner** [comment]
closing due to being a duplicate
