### ISSUE TITLE
Storjshare Daemon (Snap Install) Cannot Be Updated For ETH Address

### ISSUE THREAD

**Issue by ghost** [Storj/storjshare-daemon#171]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
Not Installed As This Is A Snap Installation
```

### Expected Behavior

Since the update is here to use ETH addresses, they have released an update so that you can put them into the config. So, you should be able to run ```sudo snap refresh storjshare``` which is the command to update a snap install, and it should update.
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.
When sudo snap storjshare refresh is ran, it says
```
snap "storjshare" has no updates available.
```
This doesn't make any sense because an update should be available as an update was released.
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Open a Linux terminal and run "sudo snap install storjshare"
2. Run the usual storjshare create commands and fill out the config file properly
3. Once it's running, enter these commands in order:
storjshare save
storjshare killall
sudo snap refresh storjshare

**Comment by Thracium** [comment]
Hello, I have the same problem here, the ETH Address not valid in a snap installation

snap info storjshare
name:      storjshare
summary:   "farm data on the Storj network."
publisher: bookchin
description: |
  Earn money by sharing your hard drive space.
  Daemon + CLI for farming data on the Storj network.
  
channels:                       
  latest/stable:    3.1.0  (22) 28MB -
  latest/candidate: 2.5.1  (11) 27MB -
  latest/beta:      2.5.1  (11) 27MB -
  latest/edge:      master (5)  27MB -

**Comment by littleskunk** [comment]
How about `snap refresh storjshare --beta`? As far as I understand that should install the latest release.

**Comment by lunarthegrey** [comment]
I have the same problem it's actually quite annoying how buggy storjshare is. I just want to make some ETH! It's like they don't even test the packages they push. It also looks like --beta is even older than --stable.

**Comment by littleskunk** [comment]
If we have to remove snap because it is not working I can do that. Storjshare is working. Only snap has a problem for some reason.

**Comment by NateDevOfficial** [comment]
Sorry I never got around to doing --beta as I just used the npm install, but I think Meije on the community chat said that it's never going to be updated as that's bookchin's job, and he left.
