### ISSUE TITLE
Incorrect storage configuration stops contracts with no error message

### ISSUE THREAD

**Issue by jmif** [Storj/storjshare-daemon#172]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.2.0, core: 6.5.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
6.9.1
```

### Expected Behavior

When I configure a share node with a storage size of `100G` (note the lack of `B`) there should be an error message saying that config is incorrect or the system should work properly and understand the space allocation.

### Actual Behavior

No error message is displayed and no contracts are obtained.  When debug logging is enabled all contract negotiation logs say `enough free space: false` even though there are many GBs of space available.  When I add the `B` to `GB` things work as expected. 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start daemon
2. Create share config with storage size `95G` and debug logging enabled
3. Note debug logs that say no space available and lack of error messages around storage size

**Comment by ssa3512** [comment]
I will take care of fixing this. Thanks for the report.
