### ISSUE TITLE
Contract Count is the Devil's work.

### ISSUE THREAD

**Issue by tempestb** [Storj/storjshare-daemon#191]
Suggest changing "Contract Count" from checking for "OFFER ACCEPTED" to consignment messages.  If you cannot do this, I suggest renaming it from Contract Count to "Message Count" since it currently means nothing but users are under the impression that they "have" contracts and they want to know why when their node resets they lose their contracts.  They also ask why they don't have any data but have 10,000 contracts.   The name "Contract Count" is dumb.  Either count consignment messages, or just call it something else please.  It would reduce confusion of farmers and the admins having to answer questions constantly about it.  It's not helpful currently.

Thanks
Kevin

**Comment by littleskunk** [comment]
Can be closed right?

**Comment by aleitner** [comment]
added offers with data received to daemon. https://github.com/Storj/storjshare-daemon/commit/1970a81974151ecc2763ba6a00f1bc2bc11d9ddb
