### ISSUE TITLE
Remove  "maxOfferConcurrency" and "offerBackoffLimit" from config file as they are deprecated

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#192]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.0.3
```

Replace the values below using the output from `node --version`.

```
6.9.1
```

### Expected Behavior

As both  "maxOfferConcurrency" and "offerBackoffLimit" are deprecated, remove them from the JSON structure when creating a new node.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
These two parameters are added to the config file even though they are deprecated.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by Puychack** [comment]
Is there any new setting that replaces the old ones ?

**Comment by MeijeSibbel** [comment]
@littleskunk , are you sure this is not deprecated?

**Comment by littleskunk** [comment]
@MeijeSibbel yes I am sure.
https://github.com/Storj/core/blob/eb006a04a355465f9419bf779c23beb93e58a6fe/lib/network/farmer.js#L126

Only `maxOfferConcurrency` can be removed.
