### ISSUE TITLE
Add "maxShardSize" to the config file by default and check validity 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#193]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.0.3
```

Replace the values below using the output from `node --version`.

```
6.9.1
```

### Expected Behavior

Currently  "maxShardSize" (e.g. "maxShardSize": "100MB") is a available parameter but has to be added manually to the config file. I suggest adding the parameter to the config by default and just set it to a default value. This way people will know its there and can change it if they want to.  

**Also**

As far as i know the the maximum shard size a node can handle depends total allocated space, a error catcher to ensure that a user doesn't set the value higher than is possible would also be nice.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by ssa3512** [comment]
Do you know what the relation between max shard size and allocated space is?
