### ISSUE TITLE
Sudden crash of nodes : "invalid payout address"

### ISSUE THREAD

**Issue by guelz** [Storj/storjshare-daemon#197]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.1.0, core: 6.6.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.0
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

All my Nodes suddenly crashed and wont restart!

` PS C:\Users\<me>> storjshare start -c C:\Users\<me>\Wallets\storj\config0.json`
`failed to start share, reason: invalid payout address`

They have been running with the same config and address since the change to ERC20 until now.

```

```

### Steps to Reproduce

Only thing that changed is that win10 asked if it please, may update itself!-)
[KB4025342](https://support.microsoft.com/en-us/help/4025342/windows-10-update-kb4025342) and [KB4025376](https://support.microsoft.com/en-us/help/4025376/security-update-for-adobe-flash-player-april-11-2017)
But the nodes crashed before I gave permission to update and restart!? 

I tried recreating the configs with different editors but always with the same outcome!

??

**Comment by subwolf** [comment]
Same happened to me after updating to 6.7.0.

https://github.com/Storj/storjshare-daemon/blob/master/lib/utils.js#L43

My payout address is 0x926b4D971B87C07B7334cdF13459234C8D84d1D5 - the migration tool sent to the same address with no problems.

**Comment by guelz** [comment]
running 
`npm install --global windows-build-tools` as admin AND
`npm install --global storjshare-daemon` again seems to have fixed it for me!

**Comment by subwolf** [comment]
Upgraded to daemon 3.5.1 with core 6.8.0, no change.

````
root@subwolf-nas:~# storjshare start -c /root/.storjshare/config.json

  failed to start share, reason: invalid payout address

root@subwolf-nas:~# cat /root/.storjshare/config.json | head -n3
{
  // Set the SJCX/BTC address for receiving contract payments
  "paymentAddress": "0x926b4D971B87C07B7334cdF13459234C8D84d1D5",

````

**Comment by littleskunk** [comment]
You are both not running the latest Version.

Please execute the following commands:
1.) `storjshare --version` should print out
```
root@storj:~# storjshare --version                                                                                                                                                                                                                               
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
```

2.) `npm list -g storjshare-daemon` should print out
```
root@storj:~# npm list -g storjshare-daemon                                                                                                                                                                                                                      
/usr/local/lib
└── storjshare-daemon@3.5.5
```

3.) `npm list storjshare-daemon` should print out
```
root@storj:~# npm list storjshare-daemon                                                                                                                                                                                                                         
/root
└── (empty)                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                 
npm ERR! code 1
```

**Comment by subwolf** [comment]
````
root@subwolf-nas:~# storjshare --version
daemon: 3.5.1, core: 6.8.0, protocol: 1.1.0
````

Updated to the latest code from git...
````
/usr/lib
└─┬ storjshare-daemon@3.5.5
  ├── fd-diskspace@1.0.0  (git+https://github.com/littleskunk/fd-diskspace.git#c339b792a3fa7b6bb3af6f004b9873f270ce729b)
  └─┬ storj-lib@6.8.0
    ├── ip@1.1.4  (git://github.com/littleskunk/node-ip.git#b1e7ec0cbff9f7841b1584e50339a774363437c0)
    ├── jsen@0.6.4  (git://github.com/bugventure/jsen.git#9e57a9d653ff4ea47d364fc37da0f1659bfb8e89)
    └── ntp-client@0.5.5  (git://github.com/bookchin/node-ntp-client.git#64a1d2318284578b90f388565de7c4b5a2441233)
````

Then...
````
root@subwolf-nas:~# storjshare start -c /root/.storjshare/config.json

  failed to start share, reason: invalid payout address
````

Payment address is 0x926b4D971B87C07B7334cdF13459234C8D84d1D5 as produced by Mist Wallet.

**Comment by littleskunk** [comment]
You still have 2 installations and you are running the old installation!

**Comment by guelz** [comment]
@subwolf and you could try running `npm install --global windows-build-tools` again before updating!
fixed for me!
@littleskunk Noob question: running  `npm install --global storjshare-daemon` again will overwrite and update my installation? right?!

**Comment by subwolf** [comment]
@guelz I would if I ran Windows on the NAS, but I don't.

````
npm ERR! notsup Unsupported platform for windows-build-tools@1.3.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
````

**Comment by littleskunk** [comment]
@guelz If you have only one installation that command will overwrite it. @subwolf has more than one installation as is still running the old installation v3.5.1.

**Comment by subwolf** [comment]
@littleskunk I just said, I updated to V3.5.5 and it still says its invalid, there is no other copy of the codebase on this system. I'll try it on the laptop at home.

**Comment by littleskunk** [comment]
@subwolf Try this:

```
root@storj:~# which storjshare
/usr/local/bin/storjshare
```

**Comment by subwolf** [comment]
````
root@subwolf-nas:~# which storjshare
/usr/bin/storjshare
````

**Comment by littleskunk** [comment]
Better uninstall all storjshare versions you have and start with a new one.

**Comment by jfnz** [comment]
How do you uninstall all storjshare versions?

I used npm to uninstall then based on the output of "locate storj" I went through and rm'd all relevant folders and bins, etc.

Still no change.

**Comment by littleskunk** [comment]
@jfnz Search this page for `which storjshare` and follow the trace on your system.

**Comment by jfnz** [comment]
Looks like I had to go through and nuke absolutely everything bar the config.

I had started with "npm uninstall --global storjshare-daemon" but that didn't fix it so had to use "sudo find / -name *storj*" and go manually delete the following:

/home/<user>/.npm/registry.npmjs.org/storj*
/usr/lib/node_modules/stor*
/home/<user>/.npm/storj*

From there I the ran "npm install --global storjshare-daemon" which seems to have fixed it.

Thanks 👍

**Comment by martinbehrens** [comment]
For the sake of completeness: I had to restart the VM too, the above alone didn't do it for me (it still threw the invalid payout address error).

**Comment by tempestb** [comment]
Stale cookies.  Can be closed.
