### ISSUE TITLE
failed to start share, reason: invalid storage size

### ISSUE THREAD

**Issue by lippoliv** [Storj/storjshare-daemon#200]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.4.2, core: 6.6.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.0
```

### Expected Behavior

While starting a docker-based storj-daemon + farmer, it should start to work with the following command: `sh -c storjshare daemon start; storjshare start -c /storj/config.json; /bin/bash`.

### Actual Behavior

```
storj_1  |   * starting daemon in background
storj_1  |
storj_1  |   failed to start share, reason: invalid storage size
```

It actually stops because of invalid storage size. To make sure it's enough, I added `df -h` and `ls -l` (for the Mounts) to the start command:

```
storj_1  | Filesystem                Size      Used Available Use% Mounted on
storj_1  | none                      5.3G      3.0G      2.0G  60% /
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /dev
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /sys/fs/cgroup
storj_1  | /dev/mapper/HDD-storj
storj_1  |                          19.6G     44.0M     18.5G   0% /storj
storj_1  | /dev/sda3                 5.3G      3.0G      2.0G  60% /etc/resolv.conf
storj_1  | /dev/sda3                 5.3G      3.0G      2.0G  60% /etc/hostname
storj_1  | /dev/sda3                 5.3G      3.0G      2.0G  60% /etc/hosts
storj_1  | shm                      64.0M         0     64.0M   0% /dev/shm
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /proc/kcore
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /proc/timer_list
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /proc/timer_stats
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /proc/sched_debug
storj_1  | tmpfs                  1005.1M         0   1005.1M   0% /sys/firmware
storj_1  | total 8
storj_1  | -rwxr-xr-x    1 node     node          2896 Jul 18 10:11 config.json
storj_1  | drwxr-xr-x    2 node     node          4096 Jul 18 09:29 storage
storj_1  |
storj_1  |   * starting daemon in background
storj_1  |
storj_1  |   failed to start share, reason: invalid storage size
```

In `config.json` the following is set: `"storageAllocation": "17GB"`. As you can see by `df -h` there are *18.5GB free* but I just want to *use 17GB*. Should be working...

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Setup new docker runner following here: https://store.docker.com/community/images/computeronix/storjshare-daemon
2. Choose alpine
3. try to run as described

**Comment by calvintam236** [comment]
might be `df` using GiB, not GB?

**Comment by lippoliv** [comment]
17GB  = 17.000 MB  
17GiB = 17408 MiB

So: If `df` shows me `GiB` instead of `GB`, 18.5GiB is way more than 17GB.

So no, that doesn't Count here

**Comment by calvintam236** [comment]
can you show how many bytes of available space? the size is calculated using the bytes, not the way you used.

if you are using docker, check what filesystem docker is using. some of them has a base image size (like vm hdd). use `docker info` to check.

**Comment by littleskunk** [comment]
We are using df -k btw but that doesn't realy change the math.

How about the storage location?

**Comment by lippoliv** [comment]
@calvintam236 

`df -k`:  
```
Filesystem            1K-blocks    Used Available Use% Mounted on
none                    5540448 3131464   2104500  60% /
tmpfs                   1029212       0   1029212   0% /dev
tmpfs                   1029212       0   1029212   0% /sys/fs/cgroup
/dev/mapper/HDD-storj  20511356   48016  19398380   1% /storj
/dev/sda3               5540448 3131464   2104500  60% /etc/hosts
shm                       65536       0     65536   0% /dev/shm
tmpfs                   1029212       0   1029212   0% /sys/firmware
```

`docker info`:  
```
Containers: 8
 Running: 3
 Paused: 0
 Stopped: 5
Images: 10
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.963 GiB
Name: v22017051573749269
ID: ZLKA:NOMY:LNNF:YNSK:SW2O:6QPE:DKBE:FLQD:NYW2:FDXV:Q33N:56QJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 xyz
 127.0.0.0/8
Live Restore Enabled: false
```

Mounted is `/srv/storj/storj` to `/storj` while `/srv/storj` is an LVM

Host `df -h`:  
```
/dev/mapper/HDD-storj                        20G     47M   19G    1% /srv/storj
```

Hopefully this info helps you.

You need to improve here. For less-experienced users it is really confusion. Because it "is enough space". Why don't you improve the message to tell the user how much space is available if you calculation results in "to less space"?

**Comment by littleskunk** [comment]
I added missing bytes to the error message. Improvement done.

Can we close that issue or would you like to know why you are getting this error message? I still don't see your `storage location`

**Comment by lippoliv** [comment]
Do you mean `"storagePath": "/storj/storage",`? 

Please remember:

> Mounted is  /srv/storj/storj  to  /storj  while  /srv/storj  is an LVM

and 

```
/dev/mapper/HDD-storj                        20G     47M   19G    1% /srv/storj
```
