### ISSUE TITLE
SJCX addresses are no longer supported. Please enter ERC20 compatible ETH wallet address

### ISSUE THREAD

**Issue by lippoliv** [Storj/storjshare-daemon#204]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.4.2, core: 6.6.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.0
```

### Expected Behavior

Create config with an Counterwallet-Adress should be OK.

### Actual Behavior

It Fails.

```
SJCX addresses are no longer supported. Please enter ERC20 compatible ETH wallet address
```

Wallet-Adress example: `1NRwsA5DMirbjXuzoy4GhYSS7HoAWEcXTs`

### Steps to Reproduce

Run `storjshare create --storj wsA5DMirbjXuzoy4GhYSS7HoAWEcXTs --size 1890GB -storage /storj/storage --noedit --logfile /storj/storj.log -o /storj/config.json`

It should work, but it doesn't. I had to use my ETH-Wallet Adress first and afterwards modify config.

**Comment by littleskunk** [comment]
It works as designed. More informations you can read here: http://blog.storj.io/post/160448088948/token-migration-plan-pt2

If you don't setup an ERC-20 address we will not send you any payouts.!

Close it please.

**Comment by lippoliv** [comment]
@littleskunk in the config (generated) the Comment says: `// Set the STORJ/ERC20 wallet address for receiving contract payments`. 

Maybe I get something wrong or that comment has to be edited.

I added my ETH wallet adress and looking Forward to receive something in the next weeks ;)

**Comment by littleskunk** [comment]
And what is the problem now. Please read the error message again. `SJCX addresses are no longer supported.` STORJ is supported. That is the new ERC-20 token.

**Comment by akostadinov** [comment]
FYI, if one has a typo, then this error message is not helpful. Better recognize between typos and bad addresses if possible.
