### ISSUE TITLE
After update storjshare gets no offers for several hours angd gets error.

### ISSUE THREAD

**Issue by Losiara** [Storj/storjshare-daemon#207]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.5.1, core: 6.7.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.1
```

### Expected Behavior

Get new offers and increase share amount

### Actual Behavior
After update no contracts came to my node.
In log often get such error. Shared amount also freezed. Before update all worked. 

```
{"level":"error","message":"failed to publish message to contact {\"userAgent\":\"6.6.0\",\"protocol\":\"1.1.0\",\"address\":\"client1.storj.ml\",\"port\":80,\"nodeID\":\"a9683cb5484892d2ba3554907ab9453031e08d3f\",\"lastSeen\":1500629157315} with topic \"0e01\", reason: \"RPC with ID `08f026c0fd024d800b4114e217c1f9806c4e8a02` timed out\"","timestamp":"2017-07-21T09:26:49.897Z"}

```

- My port is opened and forwarding is ok
- Time delta is ok
- Peers is ok

**Comment by Losiara** [comment]
Adding log file. There is also error 

```{"level":"debug","message":"we have enough free space: false","timestamp":"2017-07-21T14:53:32.710Z"}```

[a97eca23d8f079d7dfe43567ac957f8d91356af0_2017-7-21.txt](https://github.com/Storj/storjshare-daemon/files/1165887/a97eca23d8f079d7dfe43567ac957f8d91356af0_2017-7-21.txt)

**Comment by MeijeSibbel** [comment]
![capture2](https://user-images.githubusercontent.com/11735738/28493192-2579e5b4-6f0a-11e7-963e-f618addbaa60.PNG)
![capture3](https://user-images.githubusercontent.com/11735738/28493191-2579914a-6f0a-11e7-82b3-6394bf75d76b.PNG)
[86cc8c9a3b76fd331a6c2df95b4b77e3756fe5a3_2017-7-22 (2).txt](https://github.com/Storj/storjshare-daemon/files/1167514/86cc8c9a3b76fd331a6c2df95b4b77e3756fe5a3_2017-7-22.2.txt)

**Comment by MeijeSibbel** [comment]
Somehow it sets `"we have enough free space: false"` while there is enough space, @aleitner ^

**Comment by littleskunk** [comment]
I will add more debug output to core. Lets see why the math is wrong.

**Comment by littleskunk** [comment]
Please install kfs and run `kfs -d ~/.storjshare/storjshare/shares/<nodeID>/sharddata.kfs stat`

**Comment by littleskunk** [comment]
@MeijeSibbel 
KFS will split the available 3GB into 256 buckets and accept only 11MB (1000^2) per bucket. I have seen 100MB shards. A 3GB farmer will not send an OFFER on any 100MB shard.

Increasing it to 30000MB (30GB) will accept a few 100MB shards.

I added a debug log message with shard size, bucket size etc. Next release we will see how many free space each bucket has.

**Comment by MeijeSibbel** [comment]
And another user has the same problem,

[config.txt](https://github.com/Storj/storjshare-daemon/files/1167677/config.txt)
[log.txt](https://github.com/Storj/storjshare-daemon/files/1167676/log.txt)
![storjshare](https://user-images.githubusercontent.com/11735738/28494885-30c4bbe0-6f34-11e7-8bff-d9024c834e4b.png)

**Comment by littleskunk** [comment]
Moved to https://github.com/Storj/core/issues/708

This issue can be closed.
