### ISSUE TITLE
failed to start share, reason: invalid storage size

### ISSUE THREAD

**Issue by deafboy** [Storj/storjshare-daemon#208]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.5.3, core: 6.7.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

Tell me what units in what format are expected in the config file.

### Actual Behavior

```
failed to start share, reason: invalid storage size specified: 4096 
```
(or whatever other number I type in.)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upgrade from daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0 using npm
2. Start the daemon
3. Start any of your shares.

**Comment by deafboy** [comment]
Latest working version is storjshare-daemon@3.4.2
I've managed to downgrade and everything looks fine so far.

**Comment by littleskunk** [comment]
4096 is invalid for the current version. Change it to "4096B" and you can go on.

**Comment by littleskunk** [comment]
Latest release should accept both. Issue can be closed.
