### ISSUE TITLE
How can I see an earnings estimate in the CLI?

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [Storj/storjshare-daemon#211]
Hi,

How can I see an earnings estimate in CLI? 
Because today, I have to wait one month to see in my wallet (in my case I'm almost two months sharing 9,76GB and I didn't receive storjs in my ether wallet yet).
This earnings indicator will be very useful to know If I have enough disk space or if I should buy more hdd or give up.

**Comment by littleskunk** [comment]
You can run this script to calculate GBh: https://gist.github.com/littleskunk/e91148b62263d49bc9e2c9501169392b

Calculating the STORJ payout is not possible at the moment. More details here: https://github.com/Storj/bridge/issues/432

Issue can be closed.
