### ISSUE TITLE
storjshare status says "daemon is not running"

### ISSUE THREAD

**Issue by rrivv** [Storj/storjshare-daemon#214]
### Package Versions
```
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
node v6.11.1
```
### Expected Behavior
```
"storjshare status" shows status of all nodes
```
### Actual Behavior

After upgrading to the latest daemon "storjshare status" command doesn't print a table with nodes' status. It says "daemon is not running, try: storjshare daemon" but actually daemon is running and nodes are online

### Steps to Reproduce
```
1. Start nodes
2. storjshare status
```

**Comment by littleskunk** [comment]
Did you run `storjshare killall`? I assume you updated storjshare while the old version was still running. Now you try to run the storjshare status command against the old daemon. That is not going to work. Please restart daemon and farmer and try again.

**Comment by rrivv** [comment]
Cheked all nodes one by one and found where the bug was.
On one of my nodes I changed port to higher than 65536. This node crashed with an error (RangeError: "port" option should be >= 0 and < 65536). Daemon says "share xxx exited with code 1"

And after this error `storjshare status` bug occured. After `storjshare killall` and nodes restarting everything works ok.
