### ISSUE TITLE
Setup Failes

### ISSUE THREAD

**Issue by denndsd** [Storj/storjshare-daemon#216]
I cant Use the Daemon.
After install `snap install storjshare`
I want to set up a config.
`storjshare create --sjcx payout-address --storage  /path --size 5GB --rpcaddress Public IP --rpcport 4000 --maxtunnels 3  `

When i want to start the config i got the error, Invalid payout adress.
I think now its ethereum, but i only have the scxj as payout parameter.

Do you now whats wrong.

**Comment by SadTomato** [comment]
what version of storjshare do you use?
storjshare --version

**Comment by denndsd** [comment]
Ich have the following Version.
Daemon: 3.1.0 , Core 6.5.0 , protocol 1.1.0
how can i update to the newest Version ?

**Comment by SadTomato** [comment]
the latest version is daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0.
I think "npm install --global storjshare-daemon" should help (better if you have latest npm version). At least it helped me.

**Comment by denndsd** [comment]
Sorry I cant install the Daemon with your command.
In installed the newest version of node.js and npm

Here is the log: 

`loadDep:fd-diskspace → 30 ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine storj-lib@6.8.0: wanted: {"node":"^6.9.1"} (current: {"node":"4.2.6"loadDep:ntp-client → reso ▀ ╢█████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine kad@1.6.5: wanted: {"node":"4.x.x 6.x.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine kad-quasar@1.2.4: wanted: {"node":">=6.9.1"} (current: {"node":"4.2.npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
loadDep:uuid → get        ▌ ╢█████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine atbf@1.1.0: wanted: {"node":">=6.9.1"} (current: {"node":"4.2.6","npnpm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/storjshare -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare.js
/usr/local/bin/storjshare-start -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-start.js
/usr/local/bin/storjshare-stop -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-stop.js
/usr/local/bin/storjshare-restart -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-restart.js
/usr/local/bin/storjshare-status -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-status.js
/usr/local/bin/storjshare-logs -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-logs.js
/usr/local/bin/storjshare-save -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-save.js
/usr/local/bin/storjshare-destroy -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-destroy.js
/usr/local/bin/storjshare-killall -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-killall.js
/usr/local/bin/storjshare-load -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-load.js
/usr/local/bin/storjshare-daemon -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-daemon.js
/usr/local/bin/storjshare-create -> /usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-create.js

> dtrace-provider@0.8.5 install /usr/local/lib/node_modules/storjshare-daemon/node_modules/dtrace-provider
> node scripts/install.js

sh: 1: node: not found
npm WARN install:dtrace-provider@0.8.5 dtrace-provider@0.8.5 install: `node scripts/install.js`
npm WARN install:dtrace-provider@0.8.5 spawn ENOENT

> weak@1.0.1 install /usr/local/lib/node_modules/storjshare-daemon/node_modules/weak
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-87-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/storjshare-daemon/node_modules/weak
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
npm WARN install:weak@1.0.1 Exit status 1

> secp256k1@3.3.0 install /usr/local/lib/node_modules/storjshare-daemon/node_modules/secp256k1
> prebuild-install || node-gyp rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

/usr/bin/env: »node“: Datei oder Verzeichnis nicht gefunden
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-87-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/storjshare-daemon/node_modules/secp256k1
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> leveldown@1.7.2 install /usr/local/lib/node_modules/storjshare-daemon/node_modules/leveldown
> prebuild-install || node-gyp rebuild

/usr/bin/env: »node“: Datei oder Verzeichnis nicht gefunden
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-87-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/storjshare-daemon/node_modules/leveldown
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "storjshare-daemon"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.7.2 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
`

**Comment by SadTomato** [comment]
> storj-lib@6.8.0: wanted: {"node":"^6.9.1"} (current: {"node":"4.2.6"}
Your current node version is 4.2.6. 
Try this:
`nvm install v6.11.2`
`nvm use v6.11.2`
`npm install --global storjshare-daemon`

**Comment by denndsd** [comment]
Hello,

thanks for your reply.

I had to install the nvm package.
And then the node 6.11.2 
Now it failes at the `gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/leveldown/build'

`
I tried to run the command manual . 
`mkdir: cannot create directory ‘/root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/leveldown/build’: No such file or directory
`
Here the full log.


`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

root@WP-Storage:~#  npm install --global storjshare-daemon
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/root/.nvm/versions/node/v6.11.2/bin/storjshare-logs -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-logs.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-status -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-status.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-save -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-save.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-load -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-load.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-killall -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-killall.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-destroy -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-destroy.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-daemon -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-daemon.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-create -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-create.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-start -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-start.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-stop -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-stop.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare.js
/root/.nvm/versions/node/v6.11.2/bin/storjshare-restart -> /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/bin/storjshare-restart.js

> dtrace-provider@0.8.5 install /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/dtrace-provider
> node scripts/install.js

sh: 1: node: Permission denied

> weak@1.0.1 install /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/weak
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/weak/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/weak
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> leveldown@1.7.2 install /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/leveldown
> prebuild-install || node-gyp rebuild

sh: 1: prebuild-install: Permission denied
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/leveldown/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/leveldown
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/root/.nvm/versions/node/v6.11.2/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 (node_modules/storjshare-daemon/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/storjshare-daemon/node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/root/.nvm/versions/node/v6.11.2/bin/node" "/root/.nvm/versions/node/v6.11.2/bin/npm" "install" "--global" "storjshare-daemon"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.7.2 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
`

**Comment by littleskunk** [comment]
Now you try to run the installer as root. That is a security risk. Better install it as normal user with the help of `sudo`

**Comment by denndsd** [comment]
When I Use `sudo nvm install v6.11.2` I get the Error "nvm" command not found.
With root user its no Prolem and without root user i can use nvm but not wirh sudo

**Comment by SadTomato** [comment]
This is because you installed nvm as root. 
So, install nvm  with sudo, not as root (https://github.com/creationix/nvm/blob/master/README.md).
After that you could use nvm and npm without root.

**Comment by denndsd** [comment]
Okay, I have installed the nvm with sudo.
I closed the Terminal and reopend it,
But `no commend.`
the installation was successful so i dont know whats wrong.
I removed the .nvm folder and reinstalled it. without success.

**Comment by tempestb** [comment]
Stale.  For further help join https://community.storj.io and the channel #storjshare and we'll help you out.
