### ISSUE TITLE
Run the node with 1 command instead of 3 (start, stop or restart)

### ISSUE THREAD

**Issue by calvintam236** [Storj/storjshare-daemon#225]
Is it possible to make the node to `start` when config is set via args (`restart` if the storage path has data) and `stop` when `SIGTERM` is sent to the process? (1 command instead of 3 different one?)

I made a [docker image](https://hub.docker.com/r/calvintam236/storjshare/) that user feeds the command args when they create a container.

For example, I created one container with args `start -d --config xxxxxxxx`. The first run will the node receives new offers, but after restarting the container by `docker restart` / host reboot, no new offers will be received at all.

**Comment by tempestb** [comment]
You could add a script to the cron job to launch this and check if it has gone down, and then restart if it has.  We can help you with this at https://community.storj.io  join the #storjshare channel.
