### ISSUE TITLE
Storj Share does not respect allocated size limit

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#227]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
latest
```

Replace the values below using the output from `node --version`.

```
latest
```

### Expected Behavior

Storj Share respects the allocated size limit.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Storj share goes beyond the allocated size limit.
```
![bildschirmfoto vom 2017-08-11 10-01-48](https://user-images.githubusercontent.com/11735738/29206470-ffc8a100-7e79-11e7-98e1-f49be3323fd9.png)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
Dulicate: https://github.com/Storj/core/issues/675

Close it please.
