### ISSUE TITLE
Can't start storj share on a FreeBSD zfs jail dataset

### ISSUE THREAD

**Issue by danjb** [Storj/storjshare-daemon#228]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
[storj@storj ~]$ storjshare --version
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
[storj@storj ~]$ node --version
v6.11.1
```

### Expected Behavior

storjshare should start a share on a FreeBSD zfs jail dataset with sufficient free space normally

### Actual Behavior

storjshare will not start a share on a FreeBSD zfs jail dataset, complaining of insufficient space even when the dataset has sufficient free space far in excess of the requested size for the share. For example, here is the **config.json** I'm trying to start (identifying info x'ed out):

```
{
  // Set the STORJ/ERC20 wallet address for receiving contract payments
  "paymentAddress": "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  // Subscribes to the given contract topics
  // See https://storj.github.io/core/tutorial-contract-topics.html
  "opcodeSubscriptions": [
    "0f01020202",
    "0f02020202",
    "0f03020202"
  ],
  // Limits the number of pending OFFER message at one time
  "maxOfferConcurrency": 3,
  // If the seedList is empty, use this bridge to discover seeds
  // Following a transfer, also send an exchange report to this bridge
  "bridgeUri": "https://api.storj.io",
  // Known preferred seeds in form of a storj URI
  // Example: "storj://[ip.or.hostname]:[port]/[nodeid]"
  "seedList": [],
  // Interface to bind RPC server, use 0.0.0.0 for all interfaces or if you
  // have a public address, use that, else leave 127.0.0.1 and Storj Share
  // will try to determine your address
  "rpcAddress": "xxx.dyndns.net",
  // Port to bind for RPC server, make sure this is forwarded if behind a
  // NAT or firewall - otherwise Storj Share will try to punch out
  "rpcPort": 4000,
  // doNotTraverseNat: true requires you to have an external ip address.
  // You can use a proxy to gain an external IP address.
  // doNotTraverseNat: false Enables NAT traversal strategies
  // first UPnP, then reverse HTTP tunnel
  // if that fails. Disable if you are public or using dynamic DNS
  "doNotTraverseNat": true,
  // Maximum number of tunnels to provide to the network
  // Tunnels help nodes with restrictive network configurations participate
  "maxTunnels": 3,
  // Maximum number of concurrent connections to allow
  "maxConnections": 150,
  // If providing tunnels, the starting and ending port range to open for
  // them
  "tunnelGatewayRange": {
    "min": 4001,
    "max": 4003
  },
  // Number of times to retry joining the network and the wait time between
  "joinRetry": {
    "times": 3,
    "interval": 5000
  },
  // Temporarily stop sending OFFER messages if more than this number of shard
  // transfers are active
  "offerBackoffLimit": 4,
  // ECDSA private key for your network identity, your Node ID is derived from
  // this and it is used to sign and verify messages
  "networkPrivateKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  // Determines how much detail is shown in the log:
  // 4 - DEBUG | 3 - INFO | 2 - WARN | 1 - ERROR | 0 - SILENT
  "loggerVerbosity": 4,
  // Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid]_date.log
  "loggerOutputFile": "/mnt/storj/nodes/node_1/logs",
  // Directory path to store contracts and shards
  "storagePath": "/mnt/storj/nodes/node_1/storage",
  // Amount of space to lease to the network, as human readable string
  // Valid units are B, KB, MB, GB, TB
  "storageAllocation": "3GB",
  // Max size of shards that will be accepted and stored
  // Use this and make this lower if you don't have a strong internet connection
  // "maxShardSize": "100MB",
  // Periodically report your used and free capacity to Storj Labs to improve
  // the network - no personally identifiable information is sent
  "enableTelemetryReporting": true
}
```
This is trying to allocate a sample 3GB share on a zfs dataset mounted to the jail at **/mnt/storj**. This dataset has 15TB free space on it. However, when I try to start the share I get an insufficient space error:
```
[storj@storj ~]$ storjshare daemon

  * starting daemon in background
[storj@storj ~]$ storjshare status

┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬─────────┐
│ Share                                       │ Status  │ Uptime   │ Restarts │ Peers   │ Offers        │ Delta   │ Port     │ Shared  │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴─────────┘
[storj@storj ~]$ storjshare start --config /mnt/storj/nodes/node_1/config/config.json

  failed to start share, reason: invalid storage size: 3221225470 bytes missing
[storj@storj ~]$ df -H /mnt/storj/nodes/node_1/storage
Filesystem             Size    Used   Avail Capacity  Mounted on
/mnt/olddisks/storj     15T    250k     15T     0%    [restricted]
```
It looks like the free space check in storjshare is not working properly in this environment? I have full write access to that dataset (indeed the configuration file was created there by that user). I have also tried this operation as root with no different results. I also tried multiple share sizes larger and smaller than 3GB. For any size, the full size of the share is reported as missing, meaning I assume storjshare thinks this dataset has 0 free space.

Finally, if I move the share storage space to somewhere in the primary / file system of the jail (like **/home/storj**) the share operation works fine. Interestingly, the primary file system is also on a zfs dataset (a different one).

The log has nothing of interest that I could see:
```
{"level":"info","message":"got status query","timestamp":"2017-08-13T18:52:37.855Z"}
{"level":"info","message":"attempting to start share with config at path /mnt/storj/nodes/node_1/config/config.json","timestamp":"2017-08-13T18:53:37.576Z"}
```
The simplest way to fix this problem is to add an option to the configuration file to force the share operation to skip the share capacity check. This would let a user bypass the space check for situations where storjshare doesn't handle the particular filesystem properly.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Create a FreeBSD jail and a zfs dataset for the storj storage.
2. Attach the zfs dataset to the jail as mounted storage in the jail.
3. Install storjshare in the FreeBSD jail, and create a share config referencing the zfs dataset attached as mounted storage. Use any amount of storage as the share size less than the total dataset size.
4. Try to start the share and you will get the message "failed to start share, reason: invalid storage size" indicating you are missing an amount of storage equal to the whole share size.

**Comment by littleskunk** [comment]
We are using `df -k` but I assume your OS will not print out the mount point. Without the mount point we are not able to detect the size. Please fix that and try again.
```
[storj@storj ~]$ df -H /mnt/storj/nodes/node_1/storage
Filesystem             Size    Used   Avail Capacity  Mounted on
/mnt/olddisks/storj     15T    250k     15T     0%    [restricted]
```

**Comment by danjb** [comment]
Unfortunately I don't think there's a way to change this behavior in a FreeBSD zfs jail (I'm making an inquiry on another forum to find out if I can, but it doesn't look good so far). On top of that, the group there is pointing out that df is not 100% accurate for zfs pools. I suspect the same would be true of any filesystem supporting compression as well.

Thus an option to bypass the space validation would help any user with a similar situation. Hopefully an option to subtract a behavior wouldn't be too hard. Alternatively, any idea what source file does this check? Right now any user using FreeNAS to host storj in a jail is going to be dead in the water.

**Comment by littleskunk** [comment]
What is the equivalent call to get the free space and how can I detect that a FreeBDS zfs jail is used? I would prefer to add it here: https://github.com/littleskunk/fd-diskspace/blob/master/bin/index.js#L184-L206

**Comment by luzemario** [comment]
There is nothing anyone can do about ZFS free space calculation. This is 
dynamic, so not only storjshare, but all the system as whole is subject 
to variations on the space left. You can only know exactly the available 
space once the disk is full.

I am using ZFS on my NAS4Free box and this thing is inherent to ZFS. The 
free space will be dependent to the files stored.

Luzemário


Em 14-08-2017 10:22, Daniel Butterfield escreveu:

**Comment by littleskunk** [comment]
In that case `df -k` is as good as any other command. It will display the current free space. It is accurate in one direction. The free space is the minimum ZFS can store without any compression. Next restart the compression may provide additional space but I don't think that is a problem for us.

The only problem here is the missing mount point.

**Comment by braydonf** [comment]
Please try with the latest release, as the disk usage check library is different.

**Comment by Fogelholk** [comment]
Seems like it is now possible to start a node running in a jail on a mounted dataset on FreeNAS when I test it. Nice!
