### ISSUE TITLE
0% offers received is causing farmer confusion, round it up to 1%.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#231]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.0.3
```

Replace the values below using the output from `node --version`.

```
6.9.1
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
We are getting countless farmer questions why they are not getting any data, they see they are getting offers
but the 0% makes farmers think they are not actually getting any data, even though out of 500 offers they might get 1 actual shard. This leads to countless questions on rocketchat.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by niktak11** [comment]
As a hoster, I'd prefer that the field be rounded to the nearest tenth % instead. It should solve this problem and provide a little better granularity regarding each nodes success.

**Comment by littleskunk** [comment]
I see only one solution. Remove the percent calculation and display the pure number. That is the only way to avoid any confusions.
