### ISSUE TITLE
Share <nodeid> exited with code 1

### ISSUE THREAD

**Issue by niktak11** [Storj/storjshare-daemon#232]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior

Please describe the program's expected behavior.

Nodes don't exit/restart

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Daemon outputs the following errors:{"level":"info","message":"share <nodeid> exited with code 1","timestamp":"2017-08-19T01:41:51.977Z"}{"level":"info","message":"attempting to restart share with node id <nodeid>","timestamp":"2017-08-19T01:41:51.978Z"}
{"level":"info","message":"attempting to stop share with node id <nodeid>","timestamp":"2017-08-19T01:41:51.978Z"}
{"level":"info","message":"attempting to start share with config at path /nfs/storj/configs/<nodeid>.json","timestamp":"2017-08-19T01:41:52.013Z"}


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start nodes
2. Wait a few hours
3. Check daemon output and number of node restarts
4. Out of 8 nodes that I'm running, 5 have restarted twice do to this in the last ~20 hours and 2 have restarted once

I'm using the newest Linux Mint Mate LTS version btw

**Comment by niktak11** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: IO error: /nfs/storj/storj7/sharddata.kfs/145.s/000251.log: Stale file handle
    at Error (native)

**Comment by niktak11** [comment]
Update: the same logfile error just caused my daemon to crash

**Comment by tempestb** [comment]
Stale.  May be a SMB issue.
