### ISSUE TITLE
Return connection error when connection to the network failed( e.g. number of peers is stuck at 1).

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#233]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
latest
```

Replace the values below using the output from `node --version`.

```
latest
```

### Expected Behavior

I expect Storj Share to inform the user when connection to the network failed (stuck at 1 peer).

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Currently we see many users that are connected only to 1 peer (and thus Storj failed to connect to the network) but don't realize that Storj is not connected. This since novice users can't correlate the peers parameter to connectivity status.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by tempestb** [comment]
This might be stale after the recent changes and the Bridge Connected messages, etc.
