### ISSUE TITLE
failed to start share, reason: invalid payout address

### ISSUE THREAD

**Issue by jfnz** [Storj/storjshare-daemon#236]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior

Node starts

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Cannot start node, attempted to upgrade to new version of storj via npm.

Error = failed to start share, reason: invalid payout address

```
  // Set the STORJ/ERC20 wallet address for receiving contract payments
  "paymentAddress": "0x06ef96b486365f5xxxxxxxxxx42aab08842f5b3a",
```

Note: middle of wallet obscured for privacy

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Stopped storj
2. npm install --global storjshare-daemon
3. Retried, no change
4. npm uninstall --global storjshare-daemon
5. Remove relevant directories
6. Reinstalled, no change.

This same address works fine on another (newly installed) machine -- any ideas?

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/197

Close it please
