### ISSUE TITLE
Node ID Collision? 

### ISSUE THREAD

**Issue by bslayton** [Storj/storjshare-daemon#237]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior

I expected to see my IP and open port at `https://api.storj.io/contacts/1305d6335c7e6436594aa72209808e50d0a22244`.

### Actual Behavior

`https://api.storj.io/contacts/1305d6335c7e6436594aa72209808e50d0a22244` does not return the correct info about my node. It appears to be someone else's.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. `storjshare status`

Output:
```
┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬─────────┐
│ Share                                       │ Status  │ Uptime   │ Restarts │ Peers   │ Offers        │ Delta   │ Port     │ Shared  │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼─────────┤
│ 1305d6335c7e6436594aa72209808e50d0a22244    │ running │ 16m 37s  │ 0        │ 137     │ 12            │ 222ms   │ 4000     │ ...     │
│   → /mnt/storj/storj.io/                    │         │          │          │         │ 0% received   │         │ (TCP)    │ (...%)  │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴─────────┘
```
2. GET `https://api.storj.io/contacts/1305d6335c7e6436594aa72209808e50d0a22244` 

Output:
```
{
    "lastSeen": "2017-08-23T09:26:38.650Z",
    "port": 4004,
    "address": "storj.dainbentley.com",
    "userAgent": "6.8.0",
    "protocol": "1.1.0",
    "nodeID": "1305d6335c7e6436594aa72209808e50d0a22244"
}
```
3. `curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`

Output:
`96.91.31.54`

### Comments
Shouldn't "address" in the json response be my IP and shouldn't the "port" be 4000?

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/complex/issues/54

Close it please

**Comment by bslayton** [comment]
Whoops. Sorry about that. I searched but came up empty. I'm new here. Thanks for pointing me in the right direction.

I believe I figured out why the "address" was pointing to an address that didn't belong to me. I think that is the host I was tunneling through.
