### ISSUE TITLE
UPNP does not reopen port after router reboot

### ISSUE THREAD

**Issue by chymian** [Storj/storjshare-daemon#255]
### Package Versions
storjshare --version
```
daemon: 4.0.1, core: 7.0.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior
The node/daemon should make sure, that the UPNP-controlled Port is open and stays open.  
(maybe once an hour?)

### Actual Behavior
After rebooting the Router, the Port 4000/TCP stays closed.  
This renders the UPNP-Setup unusable.  
Workaround: manual configure the Port-forwarding.  

I wondered why the new node (my first one) got stuck at 2% shared Storage after a few days.  
UPNP Port was shown green in storjshare-status.  
after 2 weeks, I realized that the router-reboot (could have been a power outage as well) closed the UPNP port, even the rights-mgmt. would allow the device opening it (again) at any time.

### Steps to Reproduce

1. setup a storjshare-node  
2. give the node the rights to use UPNP on the router (here: AVM FritzBox 6490 Cable)  
3. storjshare will open the port and start mining.  
4. reboot the router  
5. port stays closed  
6. node stops mining  
IMHO:  
7. user got the impression, storjshare is a waste of time, aside from an outstanding concept ;-)  
8. luckily, it's just s bug :)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/600

Close it please.
