### ISSUE TITLE
Impossible to create a node with 8TB

### ISSUE THREAD

**Issue by AlexeyALeonov** [Storj/storjshare-daemon#256]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.0.1, core: 8.0.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.1
```

### Expected Behavior

I have a 27TB disk and want to create a node with 8TB.
I can run a node with 7.9 TB of dedicated space.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

  `"storageAllocation": "7.9TB",`
`storjshare start --config storj4.json`
```
failed to start share, reason: invalid storage size
```
I can start this node only with 7.2TB size on the fresh clean 27TB disk

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Format disk 27TB (you can use the virtual disk instead)
2. create folder "storj1"
3. create node with 7.9TB allocated space with this folder.
4. try to start this node

**Comment by mstuehlinger** [comment]
Should be fixed by #252 .
