### ISSUE TITLE
Only one peer and no offer

### ISSUE THREAD

**Issue by strahe** [Storj/storjshare-daemon#259]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 4.0.1, core: 7.0.3, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.3
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Hi, i installed storjshare with the [document](https://docs.storj.io/docs/storj-share-daemon-cli) step by step,  but i was always only one peer, sometimes more(about 40), but it will soon drop to 0 or 1.

i am sure the port forward is ok, my host is strahe.hopto.org.

![s](http://7xifoo.com1.z0.glb.clouddn.com/s.png)

**Comment by littleskunk** [comment]
:crystal_ball: please show me the logfile

**Comment by strahe** [comment]
@littleskunk  

https://o2df2d60w.qnssl.com/7785a680771a0ab98c0bc52150077a559e438630_2017-9-25.log 

I am upgrading it now.

**Comment by strahe** [comment]
@littleskunk hi, i just upgrade it, and it works for me.
