### ISSUE TITLE
Start multiple nodes at once

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-daemon#26]
On the first run I would like to start them one by one and call a storjshare command `safe running nodes` (replace the name with a better one) to safe all running nodes on a meta config. Later I would like to start all nodes at once with storjshare `restart safed nodes` (replace that one as well)

That will allow me to handle all nodes with a simple crontab / autostart entry.

**Comment by bookchin** [comment]
I just opened this a few minutes ago

**Comment by littleskunk** [comment]
https://github.com/Storj/storjshare-daemon/issues/25
