### ISSUE TITLE
"handling storage retrieve...." message does not followed by "authorizing....." message

### ISSUE THREAD

**Issue by alfag4** [Storj/storjshare-daemon#266]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.1.0, core: 8.1.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.3
```

### Expected Behavior

Following this message:
{"level":"info","message":"handling storage retrieve request from ********* hash ****","timestamp":"2017-10-02T14:33:22.998Z"}

an "authorizing upload data channel for...." message should be emitted. 

### Actual Behavior

The "authorizing upload data channel for...." message does not follows and in my log i have many messages like that.

```
{"level":"info","message":"handling storage retrieve request from *** hash ***","timestamp":"2017-10-02T14:33:22.998Z"}
{"level":"info","message":"replying to message to ***","timestamp":"2017-10-02T14:33:23.034Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.8.0\",\"protocol\":\"1.1.0\",\"address\":\"96.42.232.138\",\"port\":8000,\"nodeID\":\"***\",\"lastSeen\":1506130796947}","timestamp":"2017-10-02T14:33:27.575Z"}
```

### Steps to Reproduce

Sometimes happens sometimes not.

**Comment by littleskunk** [comment]
Works as expected. Not all storage retrieve requests are valid. If the sender is not authorized or you don't have that shard you should not allow the shard download. See https://github.com/Storj/core/blob/master/lib/network/protocol.js#L438-L444

Close the issue please.

**Comment by alfag4** [comment]
How i can see these error messages?

**Comment by littleskunk** [comment]
You can't see them without adding additional log statements.

**Comment by alfag4** [comment]
Ok thanks. Closing...
