### ISSUE TITLE
Have offers but 0 received

### ISSUE THREAD

**Issue by strahe** [Storj/storjshare-daemon#269]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.0.1, core: 8.0.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.3
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

![](https://o2df2d60w.qnssl.com/m2.png)

**Comment by 4Ykw** [comment]
This could be normal... it means that none of those offers yet removed the file. So you are still holding time against them.

Do you see anything suspicious over the logs for raising this ticket?

**Comment by strahe** [comment]
@4Ykw 
The log should be normal, 
so, how  long do I need to wait?

**Comment by 4Ykw** [comment]
You need to wait until the person that allocated space, releases it. Receives means when someone "finished" the contract of the FILE by REMOVING it from the storj distributed space.

**Comment by 4Ykw** [comment]
Also don't forget about this: https://community.storj.io/channel/announcements?msg=9itMe9JzzcqfzAqFF

**Comment by tempestb** [comment]
That's not exactly how it works, however Offers are no longer a thing and you should update your node if you haven't.  Further help can be found on the Storj.Rocketchat in the #storjshare channel.  https://community.storj.io

This thread can be closed.

**Comment by 4Ykw** [comment]
Yep, you are right. @tempestb.

I was behind latest news...

Thanks anyway.
