### ISSUE TITLE
Cannot restart my 32TB share

### ISSUE THREAD

**Issue by emx** [Storj/storjshare-daemon#271]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.1.0, core: 8.2.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior

In previous versions, I did:
```
storjshare-start --config /home/user/.config/storjshare/configs/SHARExxx.json 
```
and it worked fine. The status displayed as a percentage of my 32TB space. All was good.

### Actual Behavior

Now with the latest version I get the following error message:

```
failed to start share, reason: invalid storage size
```

### Limited to 8TB ??

If I change the share size in the json config file as follows:

```
"storageAllocation": "8TB"
```

then it starts ok.

So now the max size of a share is 8TB?

**Comment by braydonf** [comment]
It's been 8TB for quite a while.

**Comment by braydonf** [comment]
And this is a limitation because of KFS.

**Comment by emx** [comment]
Noted. Is this mentioned anywhere in the doc?

**Comment by braydonf** [comment]
I'm not sure...

**Comment by braydonf** [comment]
I didn't see anything, but it could probably be added at https://github.com/Storj/storjshare-daemon/blob/master/example/farmer.config.json#L65
