### ISSUE TITLE
Best way to keep Storj CLI up to date?

### ISSUE THREAD

**Issue by emx** [Storj/storjshare-daemon#272]
Wondering what everybody uses to keep things up to date...

I normally update manually with

```
npm install -g storjshare-daemon
storjshare restart -a
```

Is this the correct way to update?

How would you automate this on Linux, creating a **crontab** entry to execute those commands on a regular basis?

**Comment by tempestb** [comment]
Yes.  You can join us at https://community.storj.io and join the channel #storjshare and we can assist you with any questions about StorjShare or anything else about Storj.   Github is better for bug tracking, thanks!

**Comment by emx** [comment]
Noted with thanks.
