### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by Hisdad** [Storj/storjshare-daemon#286]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
5.2.0  I think. The latest upgrade as of 27 Oct 2017
```

Replace the values below using the output from `node --version`.

```
6.9.1
```

### Expected Behavior

npm install -g storjshare-daemon
to install the program
possibly a a "remove" first. Tried removing, rebooting. No luck
lots of disk space
Gentoo 

### Actual Behavior
 # npm install -g storjshare-daemon
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> scrypt@6.0.3 preinstall /usr/lib/node_modules/storjshare-daemon/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
./configure: line 1904: config.log: Permission denied
./configure: line 1914: config.log: Permission denied

/usr/bin/storjshare -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare.js
/usr/bin/storjshare-start -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-start.js
/usr/bin/storjshare-logs -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-logs.js
/usr/bin/storjshare-save -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-save.js
/usr/bin/storjshare-load -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-load.js
/usr/bin/storjshare-stop -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-stop.js
/usr/bin/storjshare-restart -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-restart.js
/usr/bin/storjshare-status -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-status.js
/usr/bin/storjshare-killall -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-killall.js
/usr/bin/storjshare-destroy -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-destroy.js
/usr/bin/storjshare-daemon -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-daemon.js
/usr/bin/storjshare-create -> /usr/lib/node_modules/storjshare-daemon/bin/storjshare-create.js

> diskusage@0.2.4 install /usr/lib/node_modules/storjshare-daemon/node_modules/diskusage
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/storjshare-daemon/node_modules/diskusage/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/storjshare-daemon/node_modules/diskusage/.node-gyp/6.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/storjshare-daemon/node_modules/diskusage/.node-gyp"

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...npm install -g storjshare-daemon
2. ...
3. ...

**Comment by Hisdad** [comment]
added unsafe-perm  

to fix it. But why now?

**Comment by braydonf** [comment]
Because npm runs as user `nobody` when root is used.

**Comment by Hisdad** [comment]
Which is why it is so stupid. I ran it as root because I WANTED TO RUN IT AS ROOT so it would install correctly under /usr WHICH IS EXACTLY WHERE I WANT IT.

I could kick these guys. storj -1, npm -2
