### ISSUE TITLE
Storjshare not installing on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by radumalica** [Storj/storjshare-daemon#296]
Did the nvm/npm installation as per documentation:

node --version
v8.9.1
npm --version
5.5.1

root@masternodes01 ~ # npm install --global storjshare-daemon
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> scrypt@6.0.3 preinstall /root/.nvm/versions/node/v8.9.1/lib/node_modules/storjshare-daemon/node_modules/scrypt
> node node-scrypt-preinstall.js

sh: 1: node: Permission denied
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! scrypt@6.0.3 preinstall: `node node-scrypt-preinstall.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-22T05_35_11_844Z-debug.log

Log contains:

7333 verbose unlock done using /root/.npm/_locks/staging-3b9356e178cfecc1.lock for /root/.nvm/versions/node/v8.9.1/lib/node_modules/.staging
7334 verbose stack Error: scrypt@6.0.3 preinstall: `node node-scrypt-preinstall.js`
7334 verbose stack spawn ENOENT
7334 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
7334 verbose stack     at emitTwo (events.js:126:13)
7334 verbose stack     at ChildProcess.emit (events.js:214:7)
7334 verbose stack     at maybeClose (internal/child_process.js:925:16)
7334 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
7335 verbose pkgid scrypt@6.0.3

**Comment by littleskunk** [comment]
Installing storjshare as root is not a good idea. Better create a new user for storjshare.

If you are sure you want to install it as root you can add `--unsafe-perm`.

Issue can be closed.
