### ISSUE TITLE
Low amount of peers

### ISSUE THREAD

**Issue by SadTomato** [Storj/storjshare-daemon#297]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.0
```

### Expected Behavior

I had constantly more then 100 peers before. So i expect the same now.

### Actual Behavior

Now I have just 10-15 peers. Shared amount reduced from 100% to 47% in few weeks.

Is this normal now?

**Comment by littleskunk** [comment]
Without a logfile there is nothing we can do.
