### ISSUE TITLE
.node-gyp folder is not created before use

### ISSUE THREAD

**Issue by Dmole** [Storj/storjshare-daemon#309]
### Package Versions
 node version;
```
v8.9.3
```

### Expected Behavior

npm install works or at least fails gracefully.

### Actual Behavior

installer loops over these 2 lines forever;
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/storjshare-daemon/node_modules/diskusage/.node-gyp/8.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/storjshare-daemon/node_modules/diskusage/.node-gyp"

```

### Steps to Reproduce

1. `npm install --global storjshare-daemon`

**Comment by braydonf** [comment]
This is an issue with npm and it's permissions when run as root.

**Comment by braydonf** [comment]
npm will use user "nobody" instead of "root" and will cause issues, see: https://docs.npmjs.com/misc/config#unsafe-perm

**Comment by Dmole** [comment]
The instructions should specify "--unsafe-perm"
