### ISSUE TITLE
Feature/Idea: data folder writing latency measurement

### ISSUE THREAD

**Issue by rrivv** [Storj/storjshare-daemon#31]
As I understand now clients with minimum ping get more contracts.

So let's imagine the following situation:

Imaging I have 24Tb rig at home, my connection is 100mbit. I want to get as much data as possible. But as my home connection ping is relatively high I get not much contracts. 

I deploy several [kvm] VPSs in a datacenter, install storjshare-daemon there and mount my 24/8 TB rig as a folder to each VPS.

### Expected Behavior
In this case:
1. My storj client has minimum ping [because it is in datacenter]
2. I get as much contracts as possible (see 1)
3. I can cope with future penalty [if it would be implemented] of the same IP, counterparty address, big data folder etc. (cause I can deploy VPSs with differen IPs and even in different datacenters and I dont see a way, how storj network can understand that all of them point to the same data rig in fact).
4. With enabled fscache on a VPS I can save the traffic on often-downloaded shards and unload my 100 mbit home connection and deploy even more VPS :)

### Actual Behavior
Why is that bad:
1. If my data rig goes offline too many shards would become unavailable.
2. The idea of a decentralized storage in fact doesnt work in such a case and I can cope with many future penalties (see point 3 above).

### Steps to Reproduce

My suggestion is to add a small [inside-daemon] latency test of a data folder. Cause imho even the slowest HDD on the same system would have much lower writing latency than even a second [storage-only] VPS in the same network [with storj-daemon VPS].

At least it would help storj more or less understand how many nodes use mounted data folder at another location.

p.s. I tested such a scheme in November and it worked fine (used NFS).

Andy aka rrivv_1 on chat

**Comment by BlackDuck888** [comment]
Will not help, a proper storage setup will fast enough all the time. For example ZFS, with nvme based zil and ssd based L2ARC and a mass of ram, need a large amount of i/o to be slow. In the Case that this will be slow i will setup a ceph backed storage.

**Comment by braydonf** [comment]
Sounds like a sybil attack, which there are several strategies to address, including upcoming proof-of-work, as described in SIP6, for adding new nodes.
