### ISSUE TITLE
Output of the storjshare status command impossible to read

### ISSUE THREAD

**Issue by babonet13** [Storj/storjshare-daemon#32]
The new release of storjshare-daemon provide the node path as information under the node id information. The problem is that the column ins not wide enough to see the end of the path (which is not very useful). See attached file.
![capture d ecran 2017-01-17 a 09 50 32](https://cloud.githubusercontent.com/assets/20139338/22013651/706f7744-dc9a-11e6-8415-6eec5711e6d2.png)

**Comment by onsightit** [comment]
For CLI, it would be nice to see an option for JSON output.
