### ISSUE TITLE
storjshare-daemon not up to date with latest core. What is upgrade policy?

### ISSUE THREAD

**Issue by kroko** [Storj/storjshare-daemon#320]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.3.0, core: 8.5.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v8.9.4
```

### Expected Behavior

`storjshare-daemon` gets core upgrade treatment same as `storjshare-gui`

### Actual Behavior

`storjshare-daemon` does not get core upgrade treatment same as `storjshare-gui`

What is the policy of updating `storjshare-daemon` to latest core?

StorjStat reports that I have outdated version. I can see that `core` has been updated to [8.6.0](https://github.com/Storj/core/releases/tag/v8.6.0) and `storjshare-gui` has received treatment of updating core (storj-lib) to this newest [8.6.0](https://github.com/Storj/storjshare-gui/releases/tag/v7.3.2). 

However Storjshare Daemon still uses 8.5.0 as seen both in releases (last release from December) as well as master branch where package dependency is [`"storj-lib": "^8.5.0",`](https://github.com/Storj/storjshare-daemon/blob/master/package.json#L78).

How am I supposed to upgrade to latest core? Simply wait till `storjshare-daemon` gets new release or should I force `storj-lib` package to ^8.6.0 manually?

Thanks.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install latest `storjshare-daemon` using `npm install storjshare-daemon -g`
2. execute `storjshare --version`
3. get `daemon: 5.3.0, core: 8.5.0, protocol: 1.2.0` where reported core version is not latest.

**Comment by stefanbenten** [comment]
Answered here: https://github.com/Storj/storjshare-daemon/issues/323#issuecomment-367289739
