### ISSUE TITLE
storjshare: command not found

### ISSUE THREAD

**Issue by aristosv** [Storj/storjshare-daemon#324]
On Debian 9.3, as root, I run the following commands
```
apt install -y ca-certificates
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
exit
nvm install --lts
apt install -y git python build-essential
npm install --unsafe-perm storjshare-daemon
```
The installation seems to have completed successfully.
I cannot run the commands below though.

root@storj:~ storjshare --version
storjshare: command not found
root@storj:~ node --version
node: command not found

What could I be doing wrong?

**Comment by littleskunk** [comment]
Upload the installation output please.

**Comment by littleskunk** [comment]
> Close your shell and open an new one. Now that you can call the nvm program, install Node.js (which comes with NPM):
> https://github.com/Storj/storjshare-daemon#gnulinux--mac-osx

Looks like you missed that step:

**Comment by aristosv** [comment]
Actually this is why I put the 'exit' command. I closed the terminal and opened a new one. Where is the installation output located?

**Comment by aristosv** [comment]
https://pastebin.com/n6i5j35i
I copied it from the terminal

**Comment by littleskunk** [comment]
You are close.
```
npm remove storjshare-daemon
npm install -g storjshare-daemon
```

Note: You need unserf-perm to install storjshare as root. That is a security risk. It would be better to install it as normal user.

**Comment by aristosv** [comment]
it works now. but then I restart, and when I run "storjshare-create" I get "storjshare-create: command not found" again.

That's weird. Why is it working only after the installation, and stops finding the command after I reboot?

**Comment by aristosv** [comment]
the file are all there, but for some reason its not working
https://pastebin.com/WpeBBDTm

**Comment by AlexeyALeonov** [comment]
Don't use the root. Never use the root.
You should install the node.js and modules with casual user.
Please, remove your npm, node.js and install all with casual user without root or sudo: https://docs.storj.io/docs/storj-share-daemon-cli#section-2-1-1-installation-of-the-required-components

If you will follow this guide it will work.

**Comment by aristosv** [comment]
ok, its working now, thanks
