### ISSUE TITLE
npm install storjshare-daemon failed in diskusage

### ISSUE THREAD

**Issue by sailershen** [Storj/storjshare-daemon#334]
It's in Centos 6 x64, python 2.7.13, 
When I run "npm install -g storjshare-daemon" as root, it said:
`npm WARN deprecated kad-logger-json@0.1.2: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad-quasar@1.2.4: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad@1.6.5: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
[  ................] - fetchMetadata: WARN deprecated kad@1.6.5: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
[  ................] - fetchMetadata: WARN deprecated kad@1.6.5: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad-memstore@0.0.1: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io
npm WARN deprecated kad-fs@0.0.4: Please upgrade to @kadenceproject/kadence - See https://kadence.github.io

> scrypt@6.0.3 preinstall /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
./configure: line 1904: config.log: Permission denied
./configure: line 1914: config.log: Permission denied

/root/.nvm/versions/node/v8.11.1/bin/storjshare -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-start -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-start.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-stop -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-stop.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-status -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-status.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-restart -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-restart.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-save -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-save.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-logs -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-logs.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-load -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-load.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-killall -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-killall.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-daemon -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-daemon.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-create -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-create.js
/root/.nvm/versions/node/v8.11.1/bin/storjshare-destroy -> /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/bin/storjshare-destroy.js

> diskusage@0.2.4 install /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/node_modules/diskusage
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/node_modules/diskusage/build'
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v8.11.1/bin/node" "/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v8.11.1/lib/node_modules/storjshare-daemon/node_modules/diskusage
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the diskusage@0.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-02T16_08_40_016Z-debug.log`

How can I get storjshare-daemon installed? Thanks.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/search?q=permission+denied&type=Issues

**Comment by sailershen** [comment]
Thanks for help  @littleskunk 
I've got it, the commands is:

`wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum -y install gcc gcc-c++ python-devel python-pip git devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
yum -y groupinstall 'Development Tools'


adduser op
su - op
scl enable python27 bash
scl enable devtoolset-2 bash

pip install --upgrade pip
pip install dataserv-client
pip install storjkademlia

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.3/install.sh | bash

#退出当前终端，重新登录。
exit
exit
exit
su - op

scl enable python27 bash
scl enable devtoolset-2 bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install --lts  # 安装node（含npm工具）
npm install --global storjshare-daemon -registry=https://registry.npm.taobao.org`
