### ISSUE TITLE
Limited and undefined number of shares support by daemon

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-daemon#36]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.1.0, core: 6.0.13, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2
```

### Expected Behavior

Either the daemon should support a virtually unlimited number of clients (perhaps limited by memory) or a published number should be provided (and perhaps multiple daemons per server supported).

### Actual Behavior

Current while attempting to start 1160 nodes, sequentially, all would appear to start, and casual tracking during the process would show progress as expected.  Coming back some time later, the daemon appeared to have dropped the first 573 (one run) nodes but had all the remaining ones.

Likewise, in another attempt, I noted having 811 nodes running, only to discover 33 running a short while later.

Likewise had 652 nodes running this morning before going to work and came back to a crashed daemon that wasn't running at all.  daemon.log contained nothing other than share restart commands, no other obvious errors.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Crank up 1000+ nodes.
2. Wait several hours for the nodes to start
3. Check the status

**Comment by CJClaude** [comment]
Note that I had the crashing problem on a server with only 16 daemons running.

**Comment by CJClaude** [comment]
And just had 650+ be working fine for an hour or so, all to just vanish minutes later.  Have posted a new issue for the crash problem.  Please focus this issue on resolveing the lost clients (farmer process) issue.

**Comment by bookchin** [comment]
> Note that I had the crashing problem on a server with only 16 daemons running.

Can you explain how you've set up these 16 daemon processes? And how many shares are running for each one?

**Comment by CJClaude** [comment]
Sorry, sloppy language carry over from CLI days.  I had 16 nodes running, one daemon.

**Comment by littleskunk** [comment]
Issue is outdated and can be closed. The current version will only run one farmer per cpu core.
