### ISSUE TITLE
Daemon crashing

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-daemon#39]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.1.0, core: 6.0.14, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2
```

### Expected Behavior

As the Master Control Program, the daemon must be 100% rock steady and reliable.

### Actual Behavior

Seeing apparently random crashes where going to check a status or version returns:   * daemon is not running, starting...

And all running processes vanish.

Had 654 processes running this evening (an event that takes well over an hour to get started due to the current speed of start commands), went to check the version for another issue, and got the infamous message.  

Daemon log file shows nothing special (tail clip):

{"level":"info","message":"attempting to restart share with node id 6d9b8b5f528ac823b3bac62e1c38cc071502f804","timestamp":"2017-01-19T00:34:35.085Z"}
{"level":"info","message":"attempting to stop share with node id 6d9b8b5f528ac823b3bac62e1c38cc071502f804","timestamp":"2017-01-19T00:34:35.087Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node28/config","timestamp":"2017-01-19T00:34:35.093Z"}
{"level":"info","message":"share bde2a8d25715d6dd5c2787902942054b2b0c157b exited with code 1","timestamp":"2017-01-19T00:34:41.131Z"}
{"level":"info","message":"attempting to restart share with node id bde2a8d25715d6dd5c2787902942054b2b0c157b","timestamp":"2017-01-19T00:34:41.132Z"}
{"level":"info","message":"attempting to stop share with node id bde2a8d25715d6dd5c2787902942054b2b0c157b","timestamp":"2017-01-19T00:34:41.132Z"}
{"level":"info","message":"attempting to start share with config at path /storji5/node08/config","timestamp":"2017-01-19T00:34:41.138Z"}
{"level":"info","message":"share bf36153e99dcd9cdbcec9c3ba133db3694695c4b exited with code 1","timestamp":"2017-01-19T00:34:47.458Z"}
{"level":"info","message":"attempting to restart share with node id bf36153e99dcd9cdbcec9c3ba133db3694695c4b","timestamp":"2017-01-19T00:34:47.458Z"}
{"level":"info","message":"attempting to stop share with node id bf36153e99dcd9cdbcec9c3ba133db3694695c4b","timestamp":"2017-01-19T00:34:47.458Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node343/config","timestamp":"2017-01-19T00:34:47.464Z"}
{"level":"info","message":"share 8069bc8bb65199ea1d17a0e34f814e8b094b9995 exited with code 1","timestamp":"2017-01-19T00:35:11.951Z"}
{"level":"info","message":"attempting to restart share with node id 8069bc8bb65199ea1d17a0e34f814e8b094b9995","timestamp":"2017-01-19T00:35:11.952Z"}
{"level":"info","message":"attempting to stop share with node id 8069bc8bb65199ea1d17a0e34f814e8b094b9995","timestamp":"2017-01-19T00:35:11.952Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node494/config","timestamp":"2017-01-19T00:35:11.958Z"}
{"level":"info","message":"share 4fc36349aa482bfee700b59eb13baab1386140a5 exited with code 1","timestamp":"2017-01-19T00:35:13.844Z"}
{"level":"info","message":"attempting to restart share with node id 4fc36349aa482bfee700b59eb13baab1386140a5","timestamp":"2017-01-19T00:35:13.845Z"}
{"level":"info","message":"attempting to stop share with node id 4fc36349aa482bfee700b59eb13baab1386140a5","timestamp":"2017-01-19T00:35:13.845Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node388/config","timestamp":"2017-01-19T00:35:13.850Z"}
{"level":"info","message":"share 9265dc5f9f013fa23418d58f3b6e95cd301336cd exited with code 1","timestamp":"2017-01-19T00:35:16.563Z"}
{"level":"info","message":"attempting to restart share with node id 9265dc5f9f013fa23418d58f3b6e95cd301336cd","timestamp":"2017-01-19T00:35:16.563Z"}
{"level":"info","message":"attempting to stop share with node id 9265dc5f9f013fa23418d58f3b6e95cd301336cd","timestamp":"2017-01-19T00:35:16.563Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node392/config","timestamp":"2017-01-19T00:35:16.573Z"}
{"level":"info","message":"share f0a8410c2c1d7e0674bc51e579e1ca12b567b47b exited with code 1","timestamp":"2017-01-19T00:35:22.996Z"}
{"level":"info","message":"attempting to restart share with node id f0a8410c2c1d7e0674bc51e579e1ca12b567b47b","timestamp":"2017-01-19T00:35:22.997Z"}
{"level":"info","message":"attempting to stop share with node id f0a8410c2c1d7e0674bc51e579e1ca12b567b47b","timestamp":"2017-01-19T00:35:22.997Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node436/config","timestamp":"2017-01-19T00:35:23.020Z"}
{"level":"info","message":"share 4362cdadf4e849ba13efcea787d78346f7c67712 exited with code 1","timestamp":"2017-01-19T00:35:23.797Z"}
{"level":"info","message":"attempting to restart share with node id 4362cdadf4e849ba13efcea787d78346f7c67712","timestamp":"2017-01-19T00:35:23.798Z"}
{"level":"info","message":"attempting to stop share with node id 4362cdadf4e849ba13efcea787d78346f7c67712","timestamp":"2017-01-19T00:35:23.798Z"}
{"level":"info","message":"attempting to start share with config at path /storji5/node49/config","timestamp":"2017-01-19T00:35:23.813Z"}

As previously reported in other issues posted this evening, this is happening with smaller daemon instances running only 16 shares as well.

Posted this issue to focus on the daemon crash issue.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by CJClaude** [comment]
Ran the daemon in foreground per Gordon's recommendation and caught this trace:

`<lots and lots of the info message>
{"level":"info","message":"share e6ee298ddd4771991a1e2ad1d26e54cd19a5afd5 exited with code 1","timestamp":"2017-01-19T02:49:54.386Z"}
{"level":"info","message":"attempting to restart share with node id e6ee298ddd4771991a1e2ad1d26e54cd19a5afd5","timestamp":"2017-01-19T02:49:54.386Z"}
{"level":"info","message":"attempting to stop share with node id e6ee298ddd4771991a1e2ad1d26e54cd19a5afd5","timestamp":"2017-01-19T02:49:54.386Z"}
{"level":"info","message":"attempting to start share with config at path /storj/node222/config","timestamp":"2017-01-19T02:49:54.392Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at WriteStream.Writable.write (_stream_writable.js:244:5)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:548:20)`

**Comment by aceman444** [comment]
Can you check what value do you have for the "loggerOutputFile" variable in your .json config of the share? Do you have empty value ("") ?

**Comment by fhirschmann** [comment]
Are you using the snap packages? I had similar behavior until I added the k flag to the LOCK file storj creates to `/var/lib/snapd/apparmor/profiles/snap.storjshare.storjshare`.
