### ISSUE TITLE
Daemon : telemetry report rejected

### ISSUE THREAD

**Issue by FredBeck** [Storj/storjshare-daemon#45]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.1.2, core: 6.0.15, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Send usual telemetry reports

### Actual Behavior

No telemetry messages in the log, only the following warnings :

```
{"level":"warn","message":"telemetry report rejected, reason: Cannot read property 'nodeID' of undefined","timestamp":"2017-01-20T16:34:05.203Z"}

```

### Steps to Reproduce

1. Update to daemon: 2.1.2 and run a node for a while
2. cat /path/to/node/log.txt | grep telem

**Comment by bookchin** [comment]
This is an issue on the receiving service side of the report, which has veen updated and will be deployed soon.

**Comment by dsutil** [comment]
Any news about this, I have the same behaviour already...

**Comment by bookchin** [comment]
* https://github.com/Storj/pullypusher/pull/7
* https://github.com/Storj/data-api/pull/7
