### ISSUE TITLE
Connection Refused on first run

### ISSUE THREAD

**Issue by subwolf** [Storj/storjshare-daemon#46]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.1.0, core: 6.0.14, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
7.4.0
```

### Expected Behavior

First start, trying to fetch status of any nodes running with ```storjshare status```.

### Actual Behavior

```
root@subwolf-nas:~# storjshare status 

  * daemon is not running, starting...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:45015
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
root@subwolf-nas:~# 
root@subwolf-nas:~# 
root@subwolf-nas:~# storjshare status 

┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
root@subwolf-nas:~# 

```

Works fine after the first try. Maybe wait a a bit longer if the daemon is not running?

**Comment by CJClaude** [comment]
Also seeing this.  Tried issuing a killall, tried waiting a few minutes:

storj@rackserv ~ $ storjshare load

  * daemon is not running, starting...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:45015
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

Waited 20 minutes and things now appear to be loading, but not getting the startup messages (watching Top with a "node" filter and see the processes being spawned)

**Comment by JeromeGillard** [comment]
Still encountering in v2.3.0.


root@JGI02:~# storjshare load

  * daemon is not running, starting...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:45015
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
root@JGI02:~# storjshare load

  * snapshot /root/.config/storjshare/snapshot loaded
root@JGI02:~# storjshare status

┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ f5782db1fc5d8c55c758d1dd95e6bb8d08dd6fb9    │ running  │ 32s      │ 0        │ 2        │ 7.32GB   │
│   → /root/.storjshare                       │          │          │          │          │ (1%)     │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
root@JGI02:~# storjshare --version

  * daemon: 2.3.0, core: 6.1.2, protocol: 1.1.0
root@JGI02:~#
