### ISSUE TITLE
failed to start share, reason: invalid payout address

### ISSUE THREAD

**Issue by bananenwilly** [Storj/storjshare-daemon#51]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.1.2, core: 6.0.15, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
6.9.4
```

### Expected Behavior

start

### Actual Behavior

storjshare start --config /srv/.storj/config.json

  failed to start share, reason: invalid payout address

### Steps to Reproduce

Is it still required to have 10.000 SJCX at that address? If yes, that might be the problem here.

**Comment by bookchin** [comment]
No requirement for balance. This is the expected behavior if you added an invalid address in your config file. Open `/srv/.storj/config.json` and make sure it is correct.

**Comment by bananenwilly** [comment]
I can assure you that address is a valid bitcoin address.

Am 26.01.2017 10:07 nachm. schrieb "Gordon Hall" <notifications@github.com>:

**Comment by bookchin** [comment]
Humor me? Check for leading or trailing whitespace?

**Comment by bananenwilly** [comment]
It was indeed a comma mix up in the config, thanks
