### ISSUE TITLE
Error: Cannot find module 'weak' (can't run the daemon)

### ISSUE THREAD

**Issue by mohammedioz** [Storj/storjshare-daemon#55]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.1.2
```

Replace the values below using the output from `node --version`.

```
6.9.4 LTS
```

### Expected Behavior

Please describe the program's expected behavior.
Giving the command to start a node -- > Behavior should be = Node started ...

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Node does not start  and gives the following error : 

module.js:471
throw err;
^

Error: Cannot find module 'weak'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at new D (C:\Users\user\AppData\Roaming\npm\node_modules\storjshare-daemon\n
ode_modules\dnode\index.js:28:20)
at Function.exports.connect (C:\Users\user\AppData\Roaming\npm\node_modules\
storjshare-daemon\node_modules\dnode\index.js:12:13)
at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\storjs
hare-daemon\bin\storjshare-killall.js:13:20)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Simply give the start command ... 

Well the problem happened on windows 7 professional 64 bit and 32 bit (two different machines) .

The first time the problem occurred I deleted (uninstalled) Node.js , git , storjshare , windows-build-tools , even after and re installing the error occurred again .... 

While installing the storjshare I get those warnings (every-time I install) : 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\storjsh
are-daemon\node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp re
build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by MeijeSibbel** [comment]
Some extra info: I have had this issue before, just installing the necessary dependencies does not solve the issue. I solved it by removing every Visual studio component that i had installed and VS installed it again.

**Comment by MeijeSibbel** [comment]
Some extra info: I had this issue before, just installing the necessary dependencies does not solve the issue. I solved it by removing every Visual studio component that i had installed and installed it again via the windows-build-tools command.

**Comment by mohammedioz** [comment]
I have literally tried everything ... uninstalled everything and reinstalled again ...

**Comment by bookchin** [comment]
What platform are you running on and did you install the build dependencies correctly?

**Comment by bookchin** [comment]
Oh I see now that it's windows. The warning about skipping deps indicates that the windows build tools are not installed. Start fresh and just follow the README instructions and you should be good to go.
