### ISSUE TITLE
Memory leak is back

### ISSUE THREAD

**Issue by goarchit** [Storj/storjshare-daemon#57]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.2.0, core: 6.1.1, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2
```

### Expected Behavior

Storj node's memory utilization should remain within operational bounds (e.g.  Can vary, but should return to some base stat occassionally)

### Actual Behavior

Now that the network "chatter" bug has been somewhat tamed I can run hundreds of nodes again.  This enables me to see patterns between nodes.  Currently seeing memory unevenly leak between shares (linux node instances).  See the "top" paste below and note that some nodes are using over 4GB of memory while others are under 1.5GB.  Base appears to be around 1.26GB as per 2nd screenshot.  This system has been running 694 nodes running for approximately 24 hours on a 56 core (hyperthreaded) 256GB dual Xeon box.

Sorted by memory usage:  http://puu.sh/tNlX2/8ce32ec94a.png

Unsorted showing base usage:  http://puu.sh/tNmIV/a529f79693.png

Suspect the leak never really went away, it was just hidden by the resent network activity slowdown.
```
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run lots of nodes for a day
2. Observe memory growth
3. ...

**Comment by goarchit** [comment]
Confirmed using nodejs 6.9.5 as well.

Of note:  memory growth is not even - it occurs in spurts.  Not enough data points to be sure, but possibly related to the network chatter problems since my system was reasonably stable until the modem congested.  Some hours after it was reset, I noticed memory usage had more than doubled.

**Comment by littleskunk** [comment]
Lets wait for https://github.com/Storj/core/issues/662 and try again.

**Comment by bookchin** [comment]
https://github.com/Storj/core/pull/663

**Comment by littleskunk** [comment]
Can be closed. Shard reaper is now running without excessive memory usage.
