### ISSUE TITLE
config file & switches have different names

### ISSUE THREAD

**Issue by dimitrisp2** [Storj/storjshare-daemon#63]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.2.0, core: 6.1.1, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior
N/A

### Actual Behavior

doNotTraverseNat should get renamed to manualportforwarding, or the other way around.
The description should be changed as well as it can be confusing to non-native english speakers:

>   // Enables NAT traversal strategies, first UPnP, then reverse HTTP tunnel
>   // if that fails. Disable if you are public or using dynamic DNS
>   "doNotTraverseNat": true,

I set this to "false", as the description states "Disable if you are public..." and I'm public, there are no closed ports to the node. It should change to "Enable if you are public.." or "Set as true if you are public..."

### Steps to Reproduce

N/A

**Comment by bookchin** [comment]
These props are passed directly to storj-lib, so let's reopen this there instead.
