### ISSUE TITLE
Telemetry report rejected, reason: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-daemon#66]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
root@storj:~# storjshare --version

  * daemon: 2.3.0, core: 6.1.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.5
```

### Expected Behavior

Please describe the program's expected behavior.

Should send valid telemetry reports

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Looks like the fixed telemetry endpoint was published today. Now we have a new error message.
```
{"level":"warn","message":"telemetry report rejected, reason: Cannot read property 'nodeID' of undefined","timestamp":"2017-02-08T22:57:01.323Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:07:01.180Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:16:59.344Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:26:59.299Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:36:59.486Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:46:59.605Z"}

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start farming.
2. Grep logfile for `telemetry`

**Comment by bookchin** [comment]
Let's reopen at the statusify repo

**Comment by littleskunk** [comment]
https://github.com/Storj/statusify/issues/8

**Comment by jaykenneth21** [comment]
telemetry report rejected, reason: Could not process report"

**Comment by kznamst** [comment]
I also got : telemetry report rejected, reason: Could not process report"
