### ISSUE TITLE
Proposed feature: rc.d startup script

### ISSUE THREAD

**Issue by max302** [Storj/storjshare-daemon#67]
Hello all,

Being that I didn't want to just hack a cron job to start storj daemon on startup, I made a more complete rc.d script that supports mostly all storjshare-daemon functions. I'm sure the BSD crowd running Storj on Freenas will enjoy this.

[https://github.com/max302/storjshare-daemon/tree/master/script](https://github.com/max302/storjshare-daemon/tree/master/script)

I haven't had time to look into how to integrate this at the time of install through npm, but that's something I'll do eventually. 

Is this good enough for a pull request?

**Comment by bookchin** [comment]
Go ahead and open the PR so it can be reviewed.
