### ISSUE TITLE
storjshare-daemon silently fails to start

### ISSUE THREAD

**Issue by JeromeGillard** [Storj/storjshare-daemon#7]
When starting this way:
```
root@JGI02:~# storjshare start --config /root/config.json
Secp256k1 bindings are not compiled. Pure JS implementation will be used.

  * starting share with config at /root/config.json
root@JGI02:~#

```
Nothing happens, but the process fails after 15-20 seconds:
```

root@JGI02:~# storjshare status

┌──────────────────────────────────────────┬─────────┬────────┬───────┬──────────┐
│ Node ID                                  │ Status  │ Uptime │ Peers │ % Shared │
├──────────────────────────────────────────┼─────────┼────────┼───────┼──────────┤
│ f**************************************9 │ stopped │ 15s    │ 0     │ ...      │
└──────────────────────────────────────────┴─────────┴────────┴───────┴──────────┘
```

Nothing (not a line) in logs by:
`root@JGI02:~# storjshare logs -i f**************************************9`
Nor by:
`root@JGI02:~# tail -f /root/.config/storjshare/logs/f**************************************9.log`

**Comment by bookchin** [comment]
What version on node are you running?

**Comment by bookchin** [comment]
also - i have added a stderr pipe to the logfile in the open pr so you can see what's going on

**Comment by JeromeGillard** [comment]
```
root@JGI02:~# storjshare --version
2.0.0
root@JGI02:~# node --version
v6.9.1
```

After restarting the whole machine, storjshare-daemon started working. I've seen some strange logs like this from pm2 logs 0:

0|storjsha |   * daemon is not running, starting...
0|storjsha |   ProcessContainerFork-start(1) does not exist, try --help

So I guess I did not stop `pm2 storjshare-cli` when migrating to `storjshare-daemon` resulting `pm2` to restart the storjshare in the mean time than the daemon...

**Comment by bookchin** [comment]
Yeah don't use PM2 with storjshare-daemon.
