### ISSUE TITLE
reported ntp delta is wrong

### ISSUE THREAD

**Issue by spiccioli** [Storj/storjshare-daemon#72]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
$ storjshare --version

  * daemon: 2.4.1, core: 6.1.3, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

``
$ node --version
v6.9.1
```

### Expected Behavior

reported ntp time delta to be correct

### Actual Behavior

```
reported time delta unrelated to current time on server.

```

### Steps to Reproduce

1. 

$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*utcnist2.colora .NIST.           1 u  753 1024  377  141.358   -1.546   0.317
-stratum2-4.NTP. 129.70.130.70    2 u  993 1024  377   27.099    1.722   0.254
+datenbitch.de   192.53.103.103   2 u  901 1024  377   21.264    0.748   0.161
-ran.as65342.net 192.36.144.23    2 u  446 1024  377   36.602    6.060   0.079
+mini.blesmrt.ne 193.204.114.232  2 u  307 1024  377    6.815    0.421   0.202

2. 

$ storjshare start -c ....

3.

$ cat .storjshare/logs/storjshared.log | grep ntp

{"level":"info","message":"clock is synchronized with ntp, delta: 2756 ms","timestamp":"2017-02-13T16:58:19.317Z"}

4.

as you can see storjshare thinks my time is out of sync by 2756 ms, while it is no more than 6ms from the most different time server configured.

First time server configured is NIST, 

server time.nist.gov
server 0.europe.pool.ntp.org
server 1.europe.pool.ntp.org
server 2.europe.pool.ntp.org
server 0.it.pool.ntp.org

**Comment by bookchin** [comment]
The NTP client used in storj-lib is [here](https://github.com/bookchin/node-ntp-client). You can open this issue there if you like. The server used is https://github.com/bookchin/node-ntp-client/blob/master/lib/ntp-client.js#L14-L15.

**Comment by spiccioli** [comment]
bookchin, just fyi, I've cloned the npt client indicated above and issued a date followed by a call to it

$ date --rfc-3339 ns && bin/node-ntp-client
2017-02-13 18:55:44.635866923+01:00
2017-02-13T17:55:44.892Z

I see around 3 tenths of a second of difference, not nearly 3 seconds

**Comment by bookchin** [comment]
There is only one method in that package and it's the one we use in storj-lib: https://github.com/Storj/core/blob/master/lib/utils.js#L273-L296

**Comment by spiccioli** [comment]
bookchin, I've put toghether this piece of code (mind you, I've never written a single line of javascript before), to test what happens asking for the time delta without the remaining code overhead:

```
#!/usr/bin/env node

var ntp = require('./lib/ntp-client.js');

/**
 * Returns the delta between system time and NTP time
 * @param {Function} callback - Called with (err, delta)
 */
getNtpTimeDelta = function() {
  var timeBeforeRequest = new Date();

  ntp.getNetworkTime(
    ntp.defaultNtpServer,
    ntp.defaultNtpPort,
    function(err, networkTime) {
      if (err) {
        return callback(err);
      }

      var timeAfterResponse = new Date();
      var latency = timeAfterResponse - timeBeforeRequest;
      var systemTime = new Date();
      var networkT = networkTime.getTime();
      var delta = networkT - Math.abs(systemTime - latency);

      //callback(null, delta);
      console.log( delta, latency, timeBeforeRequest.toISOString(), timeAfterResponse.toISOString(), new Date( networkT ).toISOString()  );
    }
  );
};

```

I've put this snippet inside node-ntp-client's directory and I've executed it with a 

node node-ntp-client/delta.js

this is its output:

```
$ node node-ntp-client/delta.js 
64 72 '2017-02-14T20:11:22.202Z' '2017-02-14T20:11:22.274Z' '2017-02-14T20:11:22.266Z'
```

So, if there aren't errors in my snippet, I'm 64 milliseconds off from a random time server (your code uses pool.ntp.org which gives back a random server near you).

Putting "time.nist.gov" instead of ntp.defaultNtpServer gives this result:

```
$ node node-ntp-client/delta.js 
124 192 '2017-02-14T20:14:47.781Z' '2017-02-14T20:14:47.973Z' '2017-02-14T20:14:47.905Z'
```

which is consistent with the fact that I'm using a far away server (I'm in Italy).

```
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*utcnist2.colora .NIST.           1 u  885 1024  377  147.329   -3.764   1.752
-stratum2-4.NTP. 129.70.130.71    2 u  185 1024  377   27.262    2.644   0.295
+datenbitch.de   192.53.103.104   2 u  988 1024  357   21.284    1.683   0.760
-ran.as65342.net 192.36.144.23    2 u  284 1024  377   39.771    8.873   0.441
+mini.blesmrt.ne 193.204.114.232  2 u  227 1024  377    6.815    1.637   0.492
```

and

```
$ date --rfc-3339 ns && node-ntp/client/bin/node-ntp-client 
2017-02-14 21:23:11.316019372+01:00
2017-02-14T20:23:11.616Z

```

Finally, starting up storjshare I get this message inside its log file:

`{"level":"info","message":"clock is synchronized with ntp, delta: 2858 ms","timestamp":"2017-02-14T20:17:26.005Z"}`

Regards.

**Comment by spiccioli** [comment]
Ok,
I think I've nailed it!  

I had 

`"doNotTraverseNat": true,`

and

`"rpcAddress": "127.0.0.1",`

even if I have a public/static IP.

With doNotTraverseNat set to false I get 

`
{"level":"info","message":"clock is synchronized with ntp, delta: 2775 ms","timestamp":"2017-02-14T21:43:50.306Z"}`

When I set it to true  I get

```
{"level":"info","message":"clock is synchronized with ntp, delta: 16 ms","timestamp":"2017-02-14T21:45:09.680Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: 23 ms","timestamp":"2017-02-14T21:56:47.654Z"}
```

I was wrongly reading this comment inside config.json

```
// Interface to bind RPC server, use 0.0.0.0 for all interfaces or if you 
// have a public address, use that, else leave 127.0.0.1 and Storj Share
// will try to determine your address
```
as "if you have a public IP you can leave 127.0.0.1... and storjshare will find your address".

Why having NAT traversal active causes a wrong time delta remains to be ascertained.

Hope this helps.

**Comment by JeromeGillard** [comment]
I also had ~2000 ms more delay in my logs than reported by `ntpdate -q pool.ntp.org`.
I had `"doNotTraverseNat": false`, but logs said I was publicly reachable.
Restarted with `"doNotTraverseNat": true` and logs repored 130ms delta.

It seems that there's indeed a bug because my node was getting very few contracts since storjshare-daemon v2.4.1, v2.4.2 and still in current v2.4.3.

P.S. issues submission are not publicly enabled on https://github.com/bookchin/node-ntp-client

**Comment by littleskunk** [comment]
@spiccioli Please open a new core issue. Lets avoid running UPnP and NTP at the same time. If we do it one by one it should be fine.

**Comment by littleskunk** [comment]
@spiccioli UPnP is not the Problem. Don't create the core issue. I will do that for you. I think I found the calculation problem already.

**Comment by littleskunk** [comment]
https://github.com/Storj/core/issues/657

**Comment by ne0ark** [comment]
I am seeing these as well:

```
 ntpstat
synchronised to NTP server (95.81.173.8) at stratum 3 
   time correct to within 35 ms
   polling server every 1024 s
```

My delta's are 1613ms and 1153ms.
