### ISSUE TITLE
Not allowing me to install Storjshare on a Ubuntu machine

### ISSUE THREAD

**Issue by schlarmanorg** [Storj/storjshare-daemon#73]
Node Version : 6.9.5

When I use the command:

`npm install --global --build-from-source storjshare-daemon`

I get this : 

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 (node_modules/storjshare-daemon/node_modules/restify/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/storjshare-daemon/node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
npm ERR! Linux 4.8.0-30-generic
npm ERR! argv "/root/.nvm/versions/node/v6.9.5/bin/node" "/root/.nvm/versions/node/v6.9.5/bin/npm" "install" "--global" "--build-from-source" "storjshare-daemon"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! leveldown@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the leveldown@1.6.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. I created a new Ubuntu 16.10 x64 on Vultr
2. I followed the installation steps for Linux on the github page up to `npm install --global --build-from-source storjshare-daemon`

**Comment by bookchin** [comment]
You are root. Recommend running as user, but if you insist, just add `--unsafe-perm` to your install command.
