### ISSUE TITLE
Daemon not removing expired shards

### ISSUE THREAD

**Issue by goarchit** [Storj/storjshare-daemon#74]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.4.1, core: 6.1.3, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
v6.9.5
```

### Expected Behavior

Daemon should remove expired shards after 24 hours.

### Actual Behavior

No shards are being removed at least not at any significant pace.

Attached are daemon status reports showing initial status immediately after upgrading to 2.4.1, and again 28+ hours later.  Also attached are Littleskunk expired shard reports.
[Issue.zip](https://github.com/Storj/storjshare-daemon/files/775541/Issue.zip)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
I see another issue. My GUI is running the shard reaper. I can see heavy IO and the used space is going down. I don't see any shard reaper log message. Lets fix that problem first. The shard reaper may have an error but is not able to write his log message.

**Comment by bookchin** [comment]
https://github.com/Storj/core/pull/663

**Comment by bookchin** [comment]
https://github.com/Storj/storjshare-daemon/pull/79

**Comment by littleskunk** [comment]
Please try again and upload the logfile at the end. The reaper should now write his log lines and any error he gets.

**Comment by goarchit** [comment]
Sorry... can't.  After 2 months of fighting the problem, I released the 37TB of space on the server for other projects.
