### ISSUE TITLE
Error: EMFILE: too many open files | Error: IO error

### ISSUE THREAD

**Issue by Anderseta** [Storj/storjshare-daemon#75]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.4.1, core: 6.1.4, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

Please describe the program's expected behavior.

```
I guess to deal with files opened and not to crash storjshare
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

Storjshare was running fine then suddenly:

fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EMFILE: too many open files, scandir '/opt/storj/sharddata.kfs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Btable.stat (/root/.nvm/versions/node/v6.9.5/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:194:23)
    at /root/.nvm/versions/node/v6.9.5/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:182:16
{"level":"error","message":"Could not get usedSpace: IO error: lock /opt/storj/sharddata.kfs/009.s/LOCK: already held by process","timestamp":"2017-02-18T16:51:24.490Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: IO error: lock /opt/storj/sharddata.kfs/009.s/LOCK: already held by process
    at Error (native)
{"level":"error","message":"Lookup operation failed to return results","timestamp":"2017-02-18T16:54:27.867Z"}
{"level":"error","message":"Lookup operation failed to return results","timestamp":"2017-02-18T16:59:31.116Z"}
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EMFILE: too many open files, scandir '/opt/storj/sharddata.kfs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Btable.stat (/root/.nvm/versions/node/v6.9.5/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:194:23)
    at /root/.nvm/versions/node/v6.9.5/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:182:16

After this storjshare stopped working.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

```
I don't really know how to reproduce, but here are the confs i used:

Confs:
"maxOfferConcurrency": 16,
"maxTunnels": 16,
"maxConnections": 400,
"tunnelGatewayRange": {
    "min": 25,
    "max": 50000
  },
"offerBackoffLimit": 17,

Could the number of concurrency be too high? 
I have followed the instructions to reduce dropped requests to < 10%, and this was the confs that worked.

Now i reduced it to 10 instead of 16 to see if it doesn't happen anymore.

```

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/kfs/issues/38

**Comment by bookchin** [comment]
https://github.com/Storj/kfs/pull/47

**Comment by Anderseta** [comment]
Last version seems to have fixed it, thank you and good job

**Comment by Altosaxophony** [comment]
Hi
As i am new to this, please excuse if post made in wrong place or something.
Please also excuse should i place here some bunch of noobish error stuff.. i am also new to storj.
But hey maybe i can help...

Storj...
# node --version
v6.10.0
# storjshare -V

  * daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0
#


 was just runnging fine today until


# ls -lt /root/.pm2/logs/storjshare-error-0.log
--- Mar  2 20:40 /root/.pm2/logs/storjshare-error-0.log
# tail /root/.pm2/logs/storjshare-error-0.log -n5
Error: EMFILE: too many open files, scandir '/snssr01_disk02/part2/storj/.storjshare/sharddata.kfs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Btable.stat (/usr/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:194:23)
    at /usr/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:182:16
#


I Dont know if this is useless or interesting, you will tell me...

**Comment by Anderseta** [comment]
I have been running the new version for 2-3 days and for me it seems to have stopped this error.

Try to update and restart your storj:
npm install --global storjshare-daemon

**Comment by littleskunk** [comment]
We have one last issue: https://github.com/Storj/core/issues/666
