### ISSUE TITLE
invalid storage size when storage is a mounted NFS folder.

### ISSUE THREAD

**Issue by Sparc0** [Storj/storjshare-daemon#78]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.4.3, core: 6.2.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
3.10.10
```

### Expected Behavior

starting share with config at /root/.config/storjshare/configs/node1.json

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
  failed to start share, reason: invalid storage size
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ```storjshare create --sjcx [address] --storage /[directory]/storj/ --size 2TB```
2. ```storjshare start --config /[directory]/.config/storjshare/configs/[bunch of numbers and letters].json```

### Temporary fix
I mounted the nfs folder elsewhere and did a symlink back to the folder i had pointed storj.

**Comment by littleskunk** [comment]
You try to share more space than you have available. `df -k` will print out the available free space. Remember that a 2TB drive has only 1.8TB space available.

btw: nodejs 3.10.10 is not supported. Please update to nodejs LTS.

**Comment by Sparc0** [comment]
there is no problem with storage. Size: 5.3T   Used:21M  Avail:5.3T   Used:1% /opt/.storj
Will try to change nodejs version see if that help. I did follow the installation instructions yesterday so i thought i had LTS version.

**Comment by littleskunk** [comment]
Please upload your config file but remove your private key.

**Comment by Sparc0** [comment]
```
{
  // Set the SJCX/BTC address for receiving contract payments
  "paymentAddress": "secretkey123",
  // Subscribes to the given contract topics
  // See https://storj.github.io/core/tutorial-contract-topics.html
  "opcodeSubscriptions": [
    "0f01020202",
    "0f02020202",
    "0f03020202"
  ],
  // Limits the number of pending OFFER message at one time
  "maxOfferConcurrency": 3,
  // If the seedList is empty, use this bridge to discover seeds
  // Following a transfer, also send an exchange report to this bridge
  "bridgeUri": "https://api.storj.io",
  // Known preferred seeds in form of a storj URI
  // Example: "storj://[ip.or.hostname]:[port]/[nodeid]"
  "seedList": [],
  // Interface to bind RPC server, use 0.0.0.0 for all interfaces or if you
  // have a public address, use that, else leave 127.0.0.1 and Storj Share
  // will try to determine your address
  "rpcAddress": "127.0.0.1",
  // Port to bind for RPC server, make sure this is forwarded if behind a
  // NAT or firewall - otherwise Storj Share will try to punch out
  "rpcPort": 4000,
  // Enables NAT traversal strategies, first UPnP, then reverse HTTP tunnel
  // if that fails. Disable if you are public or using dynamic DNS
  "doNotTraverseNat": false,
  // Maximum number of tunnels to provide to the network
  // Tunnels help nodes with restrictive network configurations participate
  "maxTunnels": 3,
  // Maximum number of concurrent connections to allow
  "maxConnections": 150,
  // If providing tunnels, the starting and ending port range to open for
  // them
  "tunnelGatewayRange": {
    "min": 4001,
    "max": 4003
  },
  // Number of times to retry joining the network and the wait time between
  "joinRetry": {
    "times": 3,
    "interval": 5000
  },
  // Temporarily stop sending OFFER messages if more than this number of shard
  // transfers are active
  "offerBackoffLimit": 4,
  // ECDSA private key for your network identity, your Node ID is derived from
  // this and it is used to sign and verify messages
  "networkPrivateKey": "secretkey123",
  // Determines how much detail is shown in the log:
  // 4 - DEBUG | 3 - INFO | 2 - WARN | 1 - ERROR | 0 - SILENT
  "loggerVerbosity": 4,
  // Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid].log
  "loggerOutputFile": "/root/.config/storjshare/logs/f0350f78243477f2fb0d2c8122d585290f446443.log",
  // Directory path to store contracts and shards
 // "storagePath": "/opt/.storj/node1/",
  "storagePath": "/root/.config/storjshare/shares/node1/node1",
  // Amount of space to lease to the network, as human readable string
  // Valid units are B, KB, MB, GB, TB
  "storageAllocation": "2TB",
  // Periodically report your used and free capacity to Storj Labs to improve
  // the network - no personally identifiable information is sent
  "enableTelemetryReporting": true
}
```

**Comment by littleskunk** [comment]
`"storagePath": "/root/.config/storjshare/shares/node1/node1"` is not a subfolder of `Size: 5.3T Used:21M Avail:5.3T Used:1% /opt/.storj`

**Comment by Sparc0** [comment]
I have subfolders inside. When i didnt have subfolders it said invalid directory when i tried to start

**Comment by littleskunk** [comment]
Full `df -k` output please

**Comment by Sparc0** [comment]
[root@torrent node1]# df -k ./
Filesystem                                1K-blocks     Used  Available      Use% Mounted on
10.240.100.200:/mnt/zfs/.storj 5601128064 21376 5601106688   1% /opt/.storj
[root@torrent node1]# df -kh ./
Filesystem                                 Size   Used Avail Use% Mounted on
10.240.100.200:/mnt/zfs/.storj  5.3T   21M  5.3T   1% /opt/.storj

**Comment by littleskunk** [comment]
`df -k` and not df -k ./

**Comment by Sparc0** [comment]
Filesystem                                     1K-blocks       Used  Available Use% Mounted on
/dev/mapper/centos_torrent-root                 18307072    4082656   14224416  23% /
devtmpfs                                          931944          0     931944   0% /dev
tmpfs                                             942180          0     942180   0% /dev/shm
tmpfs                                             942180      91200     850980  10% /run
tmpfs                                             942180          0     942180   0% /sys/fs/cgroup
/dev/sda1                                         508588     217684     290904  43% /boot
tmpfs                                             188436          0     188436   0% /run/user/0
10.240.100.200:/mnt/zfs/.storj                5601128320      21248 5601107072   1% /opt/.storj

**Comment by littleskunk** [comment]
`"storagePath": "/root/.config/storjshare/shares/node1/node1"` will match `18307072 4082656 14224416 23% /`

You have 4082656 KByte (~4GB) free space and not 2TB. The error message is correct.

**Comment by Sparc0** [comment]
No, the error message is not correct. I have done a symlink from ```/opt/.storj/node1 to /root/.config/storjshare/shares/node1/node1``` then it started to work. 

If i pointed storagePath direct to /opt/.storj/node1 it didnt work and i got invalid storage size

**Comment by Sparc0** [comment]
Think i know what the problem was.
```// Directory path to store contracts and shards
 // "storagePath": "/opt/.storj/node1/",
  "storagePath": "/root/.config/storjshare/shares/node1/node1",
```
I removed the last / in "storagePath": "/opt/.storj/node1/",
and did a comment of the other storagePath and restarted the node and it worked.
