### ISSUE TITLE
Improvement: remove snapshots

### ISSUE THREAD

**Issue by MrFancyMonocle** [Storj/storjshare-daemon#89]
### Package Versions
```
2.1.0
```
```
7.1.0
```
### Expected Behavior

Passing a directory path of shares to rpc.load, instead of a snapshot json file, would remove unnecessary complexity; as it stands snapshot.json acts as a json substitute for a file system directory and promotes the un-sane default of diasporic share configs, necessitating their management. 

### Actual Behavior
Snapshot acts as an unused abstraction on top of fs dirs.

**Comment by bookchin** [comment]
But what if my share configurations are not all in the same directory? They are often kept on the disk that is being shared except in the case of the GUI. The snapshot file is not substituting a directory of the file system. If I wanted functional parity using a directory, I'd have to individually create a symbolic link for every one of shares into a directory.

**Comment by braydonf** [comment]
Stale
