### ISSUE TITLE
Starting a share on windows opens an empty node shell

### ISSUE THREAD

**Issue by bookchin** [Storj/storjshare-daemon#9]
Still don't know how to deal with this fuckery, see https://github.com/nodejs/node/issues/9367

**Comment by computeronix** [comment]
workaround: setup storjshare as a service

http://www.nssm.cc

Have it run either storjshare directly or execute a powershell script to execute storjshare

Just make sure the account that is executed under is the same one that installed storjshare (just make sure it is not running under local system account)
