### ISSUE TITLE
Daemon Crashing 

### ISSUE THREAD

**Issue by CCTrollz** [Storj/storjshare-daemon#90]
### Package Versions

Replace the values below using the output from `storjshare --version`.
```
Daemon: 2.5.0
Core: 6.3.0
Protocol: 1.1.0
```
Replace the values below using the output from `node --version`.

```
6.10.0
```

### Expected Behavior

As the Backbone of the host nodes, the daemon needs to be stable.

### Actual Behavior

Error thrown by daemon:
```
{"level":"info","message":"share 8aa6fbe9f5445e14a2387d5fefb4fbc498200c9d exited with code 1","timestamp":"2017-03-09T00:03:03.856Z"}
{"level":"info","message":"attempting to restart share with node id 8aa6fbe9f5445e14a2387d5fefb4fbc498200c9d","timestamp":"2017-03-09T00:03:03.856Z"}
{"level":"info","message":"attempting to stop share with node id 8aa6fbe9f5445e14a2387d5fefb4fbc498200c9d","timestamp":"2017-03-09T00:03:03.856Z"}
woops
```
Error thrown by nodes
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: IO error: H:\Storj\Node3-2\sharddata.kfs\090.s/000148.logAppend: cannot write: The system cannot find the file specified.
```

    at Error (native)
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
```
To reproduce
1. ... Just run the nodes for an extended period of time.
2. ... I have no clue what causes it.
3. ...
```

**Comment by littleskunk** [comment]
What is drive H in your case? A network drive? A locate HDD? Which file system?

**Comment by CCTrollz** [comment]
Drive H is a local drive connected via SATA using the NTFS file system.

**Comment by drygoatair** [comment]
I have this same problem. I think the drive got disconnected at some point and now the file is corrupt. I've seen people suggest to repair the database but no one clearly explains how.

**Comment by braydonf** [comment]
Stale
