### ISSUE TITLE
storjshare create check valid payment address

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-daemon#96]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
6.10.0
```

### Expected Behavior

When you run storjshare create with an invalid payment address, it should say invalid payment address and error out

### Actual Behavior

When you run storjshare create with an invalid payment address, it lets you.  Then when you attempt to run the config it says invalid payment address.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storjshare create --sjcx xxxxx (invalid address)
2. It will create the config with the invalid address
3. Then when you attempt to run the config with the invalid address it doesn't let you (which is good)

**Comment by JukeboxRhino** [comment]
This issue has been closed by [commit 496bea6](https://github.com/Storj/storjshare-daemon/commit/496bea670b66453fc1f36e3db0d23698e3d6c528#diff-e5a73574de2f736a45e0ca2ce6661271)

```
A:\Code\storjshare-daemon>storjshare create --storj 14xFtqzoEiLosmZnJY83LGfc2y28nkyw5Q
SJCX addresses are no longer supported. Please enter ERC20 compatible ETH wallet address
```

Someone with access please close this issue
