### ISSUE TITLE
OpenError: Corruption: missing files in /contracts.db/

### ISSUE THREAD

**Issue by rrivv** [Storj/storjshare-daemon#97]
### Package Versions
```
daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0
node 6.9.5
```

### Actual Behavior

Trying to launch daemon, but get an error:
```
OpenError: Corruption: 3 missing files; e.g.  /mnt/storjshare2/contracts.db/004786.ldb
```
'kfs xxx compact' didn't help... (compaction worked sucsessfully but the error still here)

### Steps to Reproduce

```
004786.ldb is absent in /contracts.db/ directory
```

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/76
